In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
from statsforecast.models import AutoARIMA
from statsforecast import StatsForecast

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv("D:\\Users\\Md Mahfuzur Rahman\\Desktop\\Research\\4_model\\cleaned_combined_data.csv", parse_dates=["datetime"])
df["unique_id"] = "BD"
df.head()

,datetime,demand_mw,load_shedding,temp_mean,wspd_mean,unique_id
0,2020-01-01 03:00:00,5351,0,18.65,1.80,BD
1,2020-01-01 06:00:00,5346,0,23.73,3.00,BD
2,2020-01-01 09:00:00,6654,0,25.25,4.58,BD
3,2020-01-01 12:00:00,6750,0,21.05,2.17,BD
4,2020-01-01 15:00:00,6546,0,18.82,0.30,BD

In [4]:
df['hour'] = df['datetime'].dt.hour
df['dayofweek'] = df['datetime'].dt.dayofweek
df['month'] = df['datetime'].dt.month
df['dayofyear'] = df['datetime'].dt.dayofyear

# -----------------------------
# Cyclic time features
# -----------------------------

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

df['dow_sin'] = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos'] = np.cos(2 * np.pi * df['dayofweek'] / 7)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df['doy_sin'] = np.sin(2 * np.pi * df['dayofyear'] / 365)
df['doy_cos'] = np.cos(2 * np.pi * df['dayofyear'] / 365)


# -----------------------------
# Lag features
# -----------------------------

for lag in [1, 2, 3, 6, 12, 24, 48, 72, 168, 336]:
    df[f'lag{lag}'] = df['demand_mw'].shift(lag)


# -----------------------------
# Rolling features
# IMPORTANT: shift(1)
# prevents target leakage
# -----------------------------

past_demand = df['demand_mw'].shift(1)

for window in [6, 12, 24, 48, 168]:

    df[f'roll{window}_mean'] = (
        past_demand.rolling(window).mean()
    )

    df[f'roll{window}_std'] = (
        past_demand.rolling(window).std()
    )


# Remove NaN
df = df.dropna().reset_index(drop=True)

In [5]:
df_ext = (
    df[["datetime", "demand_mw",

        'hour_sin','hour_cos','dow_sin','dow_cos','month_sin','month_cos','doy_sin','doy_cos',
    
        'load_shedding','temp_mean','wspd_mean',
    
        'lag1','lag2','lag3','lag6','lag12','lag24','lag48','lag72','lag168','lag336',
    
        'roll6_mean','roll6_std','roll12_mean','roll12_std','roll24_mean','roll24_std',
        'roll48_mean','roll48_std','roll168_mean','roll168_std']]
    .rename(columns={"datetime": "ds", "demand_mw": "y"})
    .assign(unique_id=df["unique_id"])
)

In [6]:
def metrics(name, y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float).ravel()
    y_pred = np.asarray(y_pred, dtype=float).ravel()

    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    r2   = r2_score(y_true, y_pred)
    acc  = max(0.0, 1.0 - mape / 100.0) * 100
    return dict(Model=name,
                Accuracy=round(acc, 3),
                MAE=round(mae, 1),
                RMSE=round(rmse, 1),
                MAPE=round(mape, 3),
                R2=round(r2, 4))

results = []  # Store results for all models

In [7]:
# Sort chronologically
sorted_df = df_ext.sort_values("ds").reset_index(drop=True)

# Last 168 rows for testing
test_size = 168

test = sorted_df.iloc[-test_size:].copy()

# Remaining data
remaining_df = sorted_df.iloc[:-test_size].copy()

# Last 20% of the remaining data for training
train_size = int(len(remaining_df) * 0.20)

train = remaining_df.iloc[-train_size:].copy()

print("Train shape:", train.shape)
print("Test shape:", test.shape)

print("Train time range:",
      train["ds"].min(), "to", train["ds"].max())

print("Test time range:",
      test["ds"].min(), "to", test["ds"].max())

print("\nTrain tail:")
print(train.tail())

print("\nTest:")
print(test)

Train shape: (8421, 34)
Test shape: (168, 34)
Train time range: 2024-12-18 08:00:00 to 2025-12-24 16:00:00
Test time range: 2025-12-24 17:00:00 to 2025-12-31 23:00:00

Train tail:
                       ds      y      hour_sin  hour_cos   dow_sin   dow_cos  \
42102 2025-12-24 12:00:00  10134  1.224647e-16 -1.000000  0.974928 -0.222521
42103 2025-12-24 13:00:00  10545 -2.588190e-01 -0.965926  0.974928 -0.222521
42104 2025-12-24 14:00:00  10209 -5.000000e-01 -0.866025  0.974928 -0.222521
42105 2025-12-24 15:00:00   9967 -7.071068e-01 -0.707107  0.974928 -0.222521
42106 2025-12-24 16:00:00   9629 -8.660254e-01 -0.500000  0.974928 -0.222521

          month_sin  month_cos   doy_sin   doy_cos  ...   roll6_std  \
42102 -2.449294e-16        1.0 -0.120208  0.992749  ...  748.203560
42103 -2.449294e-16        1.0 -0.120208  0.992749  ...  649.226514
42104 -2.449294e-16        1.0 -0.120208  0.992749  ...  515.790171
42105 -2.449294e-16        1.0 -0.120208  0.992749  ...  428.190456
42106 -2.449294e-16        1.0 -0.120208  0.992749  ...  383.664437

       roll12_mean   roll12_std  roll24_mean   roll24_std  roll48_mean  \
42102  8553.750000   846.897989  9366.208333  1085.225402  9347.708333
42103  8608.416667   929.158413  9393.791667  1096.386911  9363.375000
42104  8777.833333  1082.645063  9419.083333  1116.306874  9384.479167
42105  8954.666667  1131.735219  9412.958333  1111.334860  9386.833333
42106  9139.333333  1097.760309  9413.000000  1111.356515  9376.416667

        roll48_std  roll168_mean  roll168_std  unique_id
42102  1093.122133   9195.458333  1102.232959         BD
42103  1098.997118   9215.505952  1088.322045         BD
42104  1111.954136   9234.696429  1083.128164         BD
42105  1113.610963   9248.428571  1080.752491         BD
42106  1105.601845   9254.672619  1081.861738         BD

[5 rows x 34 columns]

Test:
                       ds      y  hour_sin      hour_cos   dow_sin   dow_cos  \
42107 2025-12-24 17:00:00   9895 -0.965926 -2.588190e-01  0.974928 -0.222521
42108 2025-12-24 18:00:00  10907 -1.000000 -1.836970e-16  0.974928 -0.222521
42109 2025-12-24 19:00:00  11052 -0.965926  2.588190e-01  0.974928 -0.222521
42110 2025-12-24 20:00:00  10785 -0.866025  5.000000e-01  0.974928 -0.222521
42111 2025-12-24 21:00:00  10566 -0.707107  7.071068e-01  0.974928 -0.222521
...                   ...    ...       ...           ...       ...       ...
42270 2025-12-31 19:00:00   9865 -0.965926  2.588190e-01  0.974928 -0.222521
42271 2025-12-31 20:00:00   9740 -0.866025  5.000000e-01  0.974928 -0.222521
42272 2025-12-31 21:00:00   9691 -0.707107  7.071068e-01  0.974928 -0.222521
42273 2025-12-31 22:00:00   9286 -0.500000  8.660254e-01  0.974928 -0.222521
42274 2025-12-31 23:00:00   8808 -0.258819  9.659258e-01  0.974928 -0.222521

          month_sin  month_cos       doy_sin   doy_cos  ...   roll6_std  \
42107 -2.449294e-16        1.0 -1.202080e-01  0.992749  ...  366.673924
42108 -2.449294e-16        1.0 -1.202080e-01  0.992749  ...  311.280206
42109 -2.449294e-16        1.0 -1.202080e-01  0.992749  ...  467.317023
42110 -2.449294e-16        1.0 -1.202080e-01  0.992749  ...  576.901291
42111 -2.449294e-16        1.0 -1.202080e-01  0.992749  ...  610.376195
...             ...        ...           ...       ...  ...         ...
42270 -2.449294e-16        1.0  6.432491e-16  1.000000  ...  824.829538
42271 -2.449294e-16        1.0  6.432491e-16  1.000000  ...  776.990004
42272 -2.449294e-16        1.0  6.432491e-16  1.000000  ...  800.006917
42273 -2.449294e-16        1.0  6.432491e-16  1.000000  ...  774.570763
42274 -2.449294e-16        1.0  6.432491e-16  1.000000  ...  499.005979

        roll12_mean  roll12_std  roll24_mean   roll24_std  roll48_mean  \
42107   9315.833333  975.627149  9412.708333  1111.296363  9367.312500
42108   9519.500000  788.000981  9431.875000  1115.655834  9372.583333
42109   9771.333333  695.630954  9476.291667  1153.239011  9417.458333
42110  10008.000000  592.328226  9477.958333  1155.581445  9443.958333
42111  10149.416667  554.053240  9471.791667  1147.848156  9435.250000
...             ...         ...          ...          ...          ...
42270   8795.000000  748.793090  8865.166667  1242.921022  9118.437500
42271   8990.750000  688.664336  8823.250000  1188.088390  9112.416667
42272   9117.250000  673.877265  8773.625000  1119.092404  9088.416667
42273   9199.250000  679.265128  8729.333333  1056.595627  9064.291667
42274   9256.583333  652.407494  8679.416667   996.696540  9036.208333

        roll48_std  roll168_mean  roll168_std  unique_id
42107  1101.594592   9256.589286  1082.240166         BD
42108  1103.540411   9261.285714  1083.294201         BD
42109  1121.459516   9271.422619  1090.697538         BD
42110  1144.990383   9278.833333  1098.559518         BD
42111  1132.852406   9281.458333  1101.642524         BD
...            ...           ...          ...        ...
42270  1265.433370   9042.023810  1248.218073         BD
42271  1261.081448   9040.422619  1246.980840         BD
42272  1237.229555   9035.630952  1242.704028         BD
42273  1213.226347   9032.547619  1240.415802         BD
42274  1191.525644   9028.494048  1238.454982         BD

[168 rows x 34 columns]

In [8]:
futr_exog_df = test.drop(["y"], axis=1)
futr_exog_df.head()
futr_exog_df.shape

(168, 33)

In [9]:

# ============================================================
# 1. Different AutoARIMA configurations to test
# ============================================================

param_grid = [
    # Small search space - faster
    {
        "season_length": 24,
        "max_p": 2,
        "max_q": 2,
        "max_P": 1,
        "max_Q": 1,
        "max_order": 4,
        "approximation": True
    },

    # Medium search space
    {
        "season_length": 24,
        "max_p": 3,
        "max_q": 3,
        "max_P": 1,
        "max_Q": 1,
        "max_order": 5,
        "approximation": True
    },

    {
        "season_length": 24,
        "max_p": 4,
        "max_q": 4,
        "max_P": 2,
        "max_Q": 2,
        "max_order": 6,
        "approximation": True
    },

    # Larger search space
    {
        "season_length": 24,
        "max_p": 5,
        "max_q": 5,
        "max_P": 2,
        "max_Q": 2,
        "max_order": 8,
        "approximation": False
    }
]


# ============================================================
# 2. Time-series cross-validation
# ============================================================

results = []

for i, params in enumerate(param_grid):

    print(f"\nRunning configuration {i+1}/{len(param_grid)}")
    print(params)

    # Create AutoARIMA using current parameters
    model = AutoARIMA(
        season_length=params["season_length"],
        max_p=params["max_p"],
        max_q=params["max_q"],
        max_P=params["max_P"],
        max_Q=params["max_Q"],
        max_order=params["max_order"],
        approximation=params["approximation"],
        alias="SARIMA"
    )

    # Create StatsForecast object
    sf = StatsForecast(
        models=[model],
        freq="H"
    )

    # --------------------------------------------------------
    # Cross-validation
    #
    # h=24      -> predict next 24 hours
    # n_windows=5 -> use 5 historical validation windows
    # step_size=24 -> move forward 24 hours each time
    # --------------------------------------------------------

    cv_df = sf.cross_validation(
        df=train,
        h=24,
        n_windows=5,
        step_size=24,
        refit=True
    )

    # --------------------------------------------------------
    # Calculate RMSE
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(
            cv_df["y"],
            cv_df["SARIMA"]
        )
    )

    results.append({
        **params,
        "RMSE": rmse
    })

    print(f"RMSE = {rmse:.4f}")


# ============================================================
# 3. Show the best configuration
# ============================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "RMSE",
    ascending=True
).reset_index(drop=True)

print("\n========== BEST CONFIGURATION ==========")
print(results_df.iloc[0])

print("\n========== ALL RESULTS ==========")
print(results_df)

Running configuration 1/4
{'season_length': 24, 'max_p': 2, 'max_q': 2, 'max_P': 1, 'max_Q': 1, 'max_order': 4, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 393.1144

Running configuration 2/4
{'season_length': 24, 'max_p': 3, 'max_q': 3, 'max_P': 1, 'max_Q': 1, 'max_order': 5, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 398.9561

Running configuration 3/4
{'season_length': 24, 'max_p': 4, 'max_q': 4, 'max_P': 2, 'max_Q': 2, 'max_order': 6, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 403.7564

Running configuration 4/4
{'season_length': 24, 'max_p': 5, 'max_q': 5, 'max_P': 2, 'max_Q': 2, 'max_order': 8, 'approximation': False}

KeyboardInterrupt:

###
Running configuration 1/4 - RMSE = 393.1144

{'season_length': 24, 'max_p': 2, 'max_q': 2, 'max_P': 1, 'max_Q': 1, 'max_order': 4, 'approximation': True}


Running configuration 2/4 - RMSE = 398.9561

{'season_length': 24, 'max_p': 3, 'max_q': 3, 'max_P': 1, 'max_Q': 1, 'max_order': 5, 'approximation': True}


Running configuration 3/4 - RMSE = 403.7564

{'season_length': 24, 'max_p': 4, 'max_q': 4, 'max_P': 2, 'max_Q': 2, 'max_order': 6, 'approximation': True}

###

In [ ]:
# Get best parameters
best = results_df.iloc[0]

print("Best parameters:")
print(best)


# ------------------------------------------------------------
# Train final model using the best configuration
# ------------------------------------------------------------

final_model = AutoARIMA(
    season_length=int(best["season_length"]),
    max_p=int(best["max_p"]),
    max_q=int(best["max_q"]),
    max_P=int(best["max_P"]),
    max_Q=int(best["max_Q"]),
    max_order=int(best["max_order"]),
    approximation=bool(best["approximation"]),
    alias="SARIMA_exog"
)

sf_final = StatsForecast(
    models=[final_model],
    freq="H"
)

sf_final.fit(df=train)

In [10]:
from sklearn.ensemble import GradientBoostingRegressor

In [11]:
print("Loading data...")
df = pd.read_csv('D:\\Users\\Md Mahfuzur Rahman\\Desktop\\Research\\for_me\\cleaned_combined_data.csv')

df['datetime'] = pd.to_datetime(df['datetime'])
df = df.sort_values('datetime').reset_index(drop=True)

Loading data...

In [12]:
df['hour'] = df['datetime'].dt.hour
df['dayofweek'] = df['datetime'].dt.dayofweek
df['month'] = df['datetime'].dt.month
df['dayofyear'] = df['datetime'].dt.dayofyear

# -----------------------------
# Cyclic time features
# -----------------------------

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

df['dow_sin'] = np.sin(2 * np.pi * df['dayofweek'] / 7)
df['dow_cos'] = np.cos(2 * np.pi * df['dayofweek'] / 7)

df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

df['doy_sin'] = np.sin(2 * np.pi * df['dayofyear'] / 365)
df['doy_cos'] = np.cos(2 * np.pi * df['dayofyear'] / 365)


# -----------------------------
# Lag features
# -----------------------------

for lag in [1, 2, 3, 6, 12, 24, 48, 72, 168, 336]:
    df[f'lag{lag}'] = df['demand_mw'].shift(lag)


# -----------------------------
# Rolling features
# IMPORTANT: shift(1)
# prevents target leakage
# -----------------------------

past_demand = df['demand_mw'].shift(1)

for window in [6, 12, 24, 48, 168]:

    df[f'roll{window}_mean'] = (
        past_demand.rolling(window).mean()
    )

    df[f'roll{window}_std'] = (
        past_demand.rolling(window).std()
    )


# Remove NaN
df = df.dropna().reset_index(drop=True)

In [13]:
df.shape

(42275, 37)

In [14]:
FEATURES = [
    'hour_sin','hour_cos','dow_sin','dow_cos','month_sin','month_cos','doy_sin','doy_cos',

    'load_shedding','temp_mean','wspd_mean',

    'lag1','lag2','lag3','lag6','lag12','lag24','lag48','lag72','lag168','lag336',

    'roll6_mean','roll6_std','roll12_mean','roll12_std','roll24_mean','roll24_std',
    'roll48_mean','roll48_std','roll168_mean','roll168_std'
]

TARGET = 'demand_mw'

In [15]:
from sklearn.model_selection import train_test_split
X = df[FEATURES]
y = df[TARGET]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Reset indices for easier access
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

# Create aliases for backward compatibility
X_tr, X_te = X_train, X_test
y_tr, y_te = y_train, y_test

print(f"Train rows: {len(X_train):,}   Test rows: {len(X_test):,}")

Train rows: 33,820   Test rows: 8,455

In [18]:
from sklearn.preprocessing import StandardScaler
import torch
import numpy as np

X_scaler = StandardScaler()

# Fit scaler only on training features.
X_tr_sc = X_scaler.fit_transform(X_tr)
X_te_sc = X_scaler.transform(X_te)

# Convert features to PyTorch tensors.
X_tr_tensor = torch.tensor(X_tr_sc, dtype=torch.float32)
X_te_tensor = torch.tensor(X_te_sc, dtype=torch.float32)

# Convert target Series to PyTorch tensors.
y_tr_tensor = torch.as_tensor(
    y_tr if isinstance(y_tr, torch.Tensor) else y_tr.to_numpy(dtype=np.float32),
    dtype=torch.float32
).reshape(-1, 1)

y_te_tensor = torch.as_tensor(
    y_te if isinstance(y_te, torch.Tensor) else y_te.to_numpy(dtype=np.float32),
    dtype=torch.float32
).reshape(-1, 1)

In [19]:
import optuna
import xgboost as xgb
import numpy as np

from sklearn.metrics import mean_squared_error


# ============================================================
# 1. Create a time-based validation split
# ============================================================
# IMPORTANT:
# We use only X_tr / y_tr for Optuna.
# X_te / y_te stays completely untouched.

val_size = int(len(X_tr) * 0.20)

# Works with both pandas DataFrame/Series and NumPy arrays
if hasattr(X_tr, "iloc"):
    X_train_cv = X_tr.iloc[:-val_size]
    X_val_cv   = X_tr.iloc[-val_size:]

    y_train_cv = y_tr.iloc[:-val_size]
    y_val_cv   = y_tr.iloc[-val_size:]
else:
    X_train_cv = X_tr[:-val_size]
    X_val_cv   = X_tr[-val_size:]

    y_train_cv = y_tr[:-val_size]
    y_val_cv   = y_tr[-val_size:]


# ============================================================
# 2. Optuna objective function
# ============================================================

def objective(trial):

    # --------------------------------------------------------
    # Optuna chooses these hyperparameters automatically
    # --------------------------------------------------------

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 300, 1200, step=100
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate", 0.01, 0.10, log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 3, 8
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight", 1, 15
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.70, 1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.70, 1.0
        ),

        "gamma": trial.suggest_float(
            "gamma", 0.0, 1.0
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha", 1e-8, 1.0, log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda", 1.0, 10.0, log=True
        )
    }


    # --------------------------------------------------------
    # Create XGBoost model
    # --------------------------------------------------------

    model = xgb.XGBRegressor(
        objective="reg:squarederror",

        **params,

        random_state=42,
        tree_method="hist",
        n_jobs=-1
    )


    # --------------------------------------------------------
    # Train ONLY on earlier data
    # --------------------------------------------------------

    model.fit(
        X_train_cv,
        y_train_cv,
        verbose=False
    )


    # --------------------------------------------------------
    # Predict validation period
    # --------------------------------------------------------

    pred = model.predict(X_val_cv)


    # --------------------------------------------------------
    # Calculate RMSE
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(y_val_cv, pred)
    )

    return rmse


# ============================================================
# 3. Create Optuna study
# ============================================================

study = optuna.create_study(
    direction="minimize",
    study_name="XGBoost_Electricity_Demand"
)


# ============================================================
# 4. Start hyperparameter optimization
# ============================================================

study.optimize(
    objective,
    n_trials=50,       # Try 50 different combinations
    show_progress_bar=True
)


# ============================================================
# 5. Display best parameters
# ============================================================

print("\n==========================================")
print("BEST XGBOOST PARAMETERS")
print("==========================================")

print("Best RMSE:")
print(study.best_value)

print("\nBest Parameters:")
for key, value in study.best_params.items():
    print(f"{key}: {value}")

[I 2026-10-10 22:49:54,254] A new study created in memory with name: XGBoost_Electricity_Demand
Best trial: 0. Best value: 358.853:   2%|▏         | 1/50 [00:01<00:56,  1.15s/it]

[I 2026-10-10 22:49:55,398] Trial 0 finished with value: 358.8527836209439 and parameters: {'n_estimators': 600, 'learning_rate': 0.04904969459352593, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.7159208457656921, 'colsample_bytree': 0.7528124597361439, 'gamma': 0.08540706619896865, 'reg_alpha': 2.159375545285861e-07, 'reg_lambda': 5.04503893330736}. Best is trial 0 with value: 358.8527836209439.

Best trial: 1. Best value: 348.812:   4%|▍         | 2/50 [00:07<03:27,  4.32s/it]

[I 2026-10-10 22:50:01,939] Trial 1 finished with value: 348.81216963790126 and parameters: {'n_estimators': 700, 'learning_rate': 0.0171404802144957, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9073570433517572, 'colsample_bytree': 0.8730739833545076, 'gamma': 0.31870048423212016, 'reg_alpha': 0.47470759438496474, 'reg_lambda': 4.755368231294168}. Best is trial 1 with value: 348.81216963790126.

Best trial: 2. Best value: 342.393:   6%|▌         | 3/50 [00:13<04:04,  5.20s/it]

[I 2026-10-10 22:50:08,187] Trial 2 finished with value: 342.39307181220823 and parameters: {'n_estimators': 600, 'learning_rate': 0.024368706023607196, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.810383333884883, 'colsample_bytree': 0.8726540360137267, 'gamma': 0.44738493460441897, 'reg_alpha': 0.024350153400286356, 'reg_lambda': 6.986935577984645}. Best is trial 2 with value: 342.39307181220823.

Best trial: 2. Best value: 342.393:   8%|▊         | 4/50 [00:32<08:02, 10.49s/it]

[I 2026-10-10 22:50:26,785] Trial 3 finished with value: 359.1333644170366 and parameters: {'n_estimators': 1200, 'learning_rate': 0.09027730377512029, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9762924281855815, 'colsample_bytree': 0.8740115105515779, 'gamma': 0.768838050085599, 'reg_alpha': 0.007363271211447995, 'reg_lambda': 1.058363988914976}. Best is trial 2 with value: 342.39307181220823.

Best trial: 2. Best value: 342.393:  10%|█         | 5/50 [00:34<05:27,  7.29s/it]

[I 2026-10-10 22:50:28,394] Trial 4 finished with value: 357.31827767761894 and parameters: {'n_estimators': 1200, 'learning_rate': 0.02511325191697111, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.9302491326919218, 'colsample_bytree': 0.7491847941624479, 'gamma': 0.8126675488263089, 'reg_alpha': 0.22774786582581913, 'reg_lambda': 8.215625982094608}. Best is trial 2 with value: 342.39307181220823.

Best trial: 5. Best value: 335.141:  12%|█▏        | 6/50 [00:43<05:44,  7.83s/it]

[I 2026-10-10 22:50:37,266] Trial 5 finished with value: 335.1408752301038 and parameters: {'n_estimators': 800, 'learning_rate': 0.04651517215949269, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9212523206019716, 'colsample_bytree': 0.8459492982523213, 'gamma': 0.9270892016020218, 'reg_alpha': 2.0699735344585455e-06, 'reg_lambda': 2.073457009639485}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  14%|█▍        | 7/50 [00:56<06:49,  9.52s/it]

[I 2026-10-10 22:50:50,284] Trial 6 finished with value: 337.0445538055763 and parameters: {'n_estimators': 1200, 'learning_rate': 0.012618958173126046, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7469361350101087, 'colsample_bytree': 0.8706415962195928, 'gamma': 0.955578717182884, 'reg_alpha': 0.002122268440898509, 'reg_lambda': 8.578829385698278}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  16%|█▌        | 8/50 [01:12<08:15, 11.81s/it]

[I 2026-10-10 22:51:06,990] Trial 7 finished with value: 349.5250348687487 and parameters: {'n_estimators': 1000, 'learning_rate': 0.025253978492853234, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8894085257217197, 'colsample_bytree': 0.9702755567568809, 'gamma': 0.8561939197083694, 'reg_alpha': 0.00336948181357567, 'reg_lambda': 2.1881701091912946}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  18%|█▊        | 9/50 [01:13<05:46,  8.46s/it]

[I 2026-10-10 22:51:08,091] Trial 8 finished with value: 337.049664830719 and parameters: {'n_estimators': 600, 'learning_rate': 0.05504686697004905, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9447538069500343, 'colsample_bytree': 0.9053709870370582, 'gamma': 0.7266212526975199, 'reg_alpha': 3.5622047833739125e-05, 'reg_lambda': 6.5275442738262095}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  20%|██        | 10/50 [01:14<04:06,  6.15s/it]

[I 2026-10-10 22:51:09,073] Trial 9 finished with value: 395.27039795562735 and parameters: {'n_estimators': 900, 'learning_rate': 0.012463592081976936, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8825324549973426, 'colsample_bytree': 0.790084044304917, 'gamma': 0.5803457764393614, 'reg_alpha': 0.21880370360955456, 'reg_lambda': 8.558543786349738}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  22%|██▏       | 11/50 [01:16<03:00,  4.63s/it]

[I 2026-10-10 22:51:10,264] Trial 10 finished with value: 347.79369333701266 and parameters: {'n_estimators': 300, 'learning_rate': 0.08534755746755272, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.8018699838664618, 'colsample_bytree': 0.9985917460963126, 'gamma': 0.020995229863731313, 'reg_alpha': 1.746278314629404e-08, 'reg_lambda': 2.4235155377064275}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  24%|██▍       | 12/50 [01:18<02:37,  4.13s/it]

[I 2026-10-10 22:51:13,250] Trial 11 finished with value: 341.61007788485983 and parameters: {'n_estimators': 900, 'learning_rate': 0.01049072345666733, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.7154944865592683, 'colsample_bytree': 0.8118997376998369, 'gamma': 0.9939555702261977, 'reg_alpha': 3.475775791999611e-05, 'reg_lambda': 2.317226027575714}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  26%|██▌       | 13/50 [01:26<03:06,  5.03s/it]

[I 2026-10-10 22:51:20,351] Trial 12 finished with value: 337.75341180734205 and parameters: {'n_estimators': 1000, 'learning_rate': 0.039557690187765296, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.8128470981041355, 'colsample_bytree': 0.8294178198186957, 'gamma': 0.9737218862366123, 'reg_alpha': 7.148074779030529e-05, 'reg_lambda': 1.0446178913230102}. Best is trial 5 with value: 335.1408752301038.

Best trial: 5. Best value: 335.141:  28%|██▊       | 14/50 [01:32<03:10,  5.30s/it]

[I 2026-10-10 22:51:26,276] Trial 13 finished with value: 382.16292337169494 and parameters: {'n_estimators': 300, 'learning_rate': 0.016271205962117317, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.7640083365285048, 'colsample_bytree': 0.7025598109304828, 'gamma': 0.6563359406464643, 'reg_alpha': 9.29016312907154e-07, 'reg_lambda': 1.611862513292608}. Best is trial 5 with value: 335.1408752301038.

Best trial: 14. Best value: 334.699:  30%|███       | 15/50 [01:38<03:21,  5.77s/it]

[I 2026-10-10 22:51:33,134] Trial 14 finished with value: 334.6992703345796 and parameters: {'n_estimators': 800, 'learning_rate': 0.035467556926158994, 'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.845077905837345, 'colsample_bytree': 0.9250445463849173, 'gamma': 0.8957372862968136, 'reg_alpha': 0.0009364584945189034, 'reg_lambda': 4.03541563341011}. Best is trial 14 with value: 334.6992703345796.

Best trial: 15. Best value: 331.21:  32%|███▏      | 16/50 [01:46<03:35,  6.33s/it]

[I 2026-10-10 22:51:40,755] Trial 15 finished with value: 331.21046933936134 and parameters: {'n_estimators': 800, 'learning_rate': 0.036688455194975135, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8647636728030332, 'colsample_bytree': 0.9365986626411585, 'gamma': 0.8731098721841292, 'reg_alpha': 2.3193612052025086e-06, 'reg_lambda': 3.905037401961594}. Best is trial 15 with value: 331.21046933936134.

Best trial: 15. Best value: 331.21:  34%|███▍      | 17/50 [01:53<03:32,  6.45s/it]

[I 2026-10-10 22:51:47,499] Trial 16 finished with value: 331.73426865489796 and parameters: {'n_estimators': 500, 'learning_rate': 0.034672310535625674, 'max_depth': 6, 'min_child_weight': 12, 'subsample': 0.8545484577837432, 'colsample_bytree': 0.9350845348863066, 'gamma': 0.5605058595167067, 'reg_alpha': 0.0004271464240076404, 'reg_lambda': 3.5514295561511786}. Best is trial 15 with value: 331.21046933936134.

Best trial: 15. Best value: 331.21:  36%|███▌      | 18/50 [02:18<06:22, 11.96s/it]

[I 2026-10-10 22:52:12,279] Trial 17 finished with value: 344.1877780550902 and parameters: {'n_estimators': 400, 'learning_rate': 0.0637056774022676, 'max_depth': 7, 'min_child_weight': 12, 'subsample': 0.8549924974600177, 'colsample_bytree': 0.9480736163037926, 'gamma': 0.4901261695781926, 'reg_alpha': 0.00023753890125999144, 'reg_lambda': 3.3135721519510257}. Best is trial 15 with value: 331.21046933936134.

Best trial: 18. Best value: 329.239:  38%|███▊      | 19/50 [02:36<07:12, 13.95s/it]

[I 2026-10-10 22:52:30,877] Trial 18 finished with value: 329.2388238422073 and parameters: {'n_estimators': 500, 'learning_rate': 0.031993910439672577, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8542348385694261, 'colsample_bytree': 0.9214288844834438, 'gamma': 0.416312930501314, 'reg_alpha': 4.181718777684627e-06, 'reg_lambda': 3.121893697038077}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  40%|████      | 20/50 [02:40<05:30, 11.02s/it]

[I 2026-10-10 22:52:35,050] Trial 19 finished with value: 332.90748057831325 and parameters: {'n_estimators': 500, 'learning_rate': 0.02928925185913589, 'max_depth': 7, 'min_child_weight': 15, 'subsample': 0.9850290319802941, 'colsample_bytree': 0.9738159553851259, 'gamma': 0.19361584623783817, 'reg_alpha': 4.634855062378615e-06, 'reg_lambda': 2.9424347193120397}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  42%|████▏     | 21/50 [02:54<05:41, 11.77s/it]

[I 2026-10-10 22:52:48,589] Trial 20 finished with value: 330.33969258931023 and parameters: {'n_estimators': 700, 'learning_rate': 0.019339388384023687, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.7801944077622447, 'colsample_bytree': 0.9047885802143556, 'gamma': 0.33894561937071255, 'reg_alpha': 6.784567415196482e-08, 'reg_lambda': 1.5564416219132196}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  44%|████▍     | 22/50 [03:07<05:41, 12.19s/it]

[I 2026-10-10 22:53:01,762] Trial 21 finished with value: 332.1803915043752 and parameters: {'n_estimators': 700, 'learning_rate': 0.019667126886649924, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.7719865740557661, 'colsample_bytree': 0.8979374339420975, 'gamma': 0.3269384827769235, 'reg_alpha': 5.372970425530166e-08, 'reg_lambda': 1.5037678083971862}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  46%|████▌     | 23/50 [03:11<04:18,  9.58s/it]

[I 2026-10-10 22:53:05,262] Trial 22 finished with value: 331.5368569254405 and parameters: {'n_estimators': 700, 'learning_rate': 0.019393891788267368, 'max_depth': 7, 'min_child_weight': 15, 'subsample': 0.8413540086002198, 'colsample_bytree': 0.9119291467540264, 'gamma': 0.3463437102358454, 'reg_alpha': 2.881716399833994e-07, 'reg_lambda': 1.526102516393263}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  48%|████▊     | 24/50 [03:17<03:48,  8.78s/it]

[I 2026-10-10 22:53:12,172] Trial 23 finished with value: 331.3028377670496 and parameters: {'n_estimators': 500, 'learning_rate': 0.0309833297271173, 'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.7846022002779333, 'colsample_bytree': 0.9551836550598767, 'gamma': 0.17429193158921627, 'reg_alpha': 7.313892529053494e-06, 'reg_lambda': 5.162523013437493}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  50%|█████     | 25/50 [03:25<03:30,  8.42s/it]

[I 2026-10-10 22:53:19,754] Trial 24 finished with value: 337.8572183630239 and parameters: {'n_estimators': 800, 'learning_rate': 0.06801485709193482, 'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.8263439669080419, 'colsample_bytree': 0.8969381799464161, 'gamma': 0.419003167961581, 'reg_alpha': 2.669372588078449e-07, 'reg_lambda': 1.8192427156182847}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  52%|█████▏    | 26/50 [03:37<03:47,  9.47s/it]

[I 2026-10-10 22:53:31,669] Trial 25 finished with value: 334.520353921103 and parameters: {'n_estimators': 400, 'learning_rate': 0.04231443804144796, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.8792114413257612, 'colsample_bytree': 0.9954609974401549, 'gamma': 0.23150781195504955, 'reg_alpha': 1.928950139388192e-08, 'reg_lambda': 1.2721997658995785}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  54%|█████▍    | 27/50 [03:43<03:15,  8.49s/it]

[I 2026-10-10 22:53:37,858] Trial 26 finished with value: 333.3784565812554 and parameters: {'n_estimators': 900, 'learning_rate': 0.021355487520336093, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.7409422013472949, 'colsample_bytree': 0.9246014458964106, 'gamma': 0.672390393007786, 'reg_alpha': 8.81581024720913e-06, 'reg_lambda': 2.7144578463380573}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  56%|█████▌    | 28/50 [03:50<02:57,  8.05s/it]

[I 2026-10-10 22:53:44,887] Trial 27 finished with value: 330.6300921157964 and parameters: {'n_estimators': 700, 'learning_rate': 0.0300757023114002, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.7919693105157957, 'colsample_bytree': 0.9534201681321589, 'gamma': 0.2522912563068536, 'reg_alpha': 6.988790528050848e-08, 'reg_lambda': 4.235445485472086}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  58%|█████▊    | 29/50 [03:58<02:49,  8.05s/it]

[I 2026-10-10 22:53:52,953] Trial 28 finished with value: 340.78552410203696 and parameters: {'n_estimators': 600, 'learning_rate': 0.029190412060804912, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.7910750346029832, 'colsample_bytree': 0.9660663646873852, 'gamma': 0.28401672098044856, 'reg_alpha': 6.870266045913056e-08, 'reg_lambda': 5.926629742726742}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  60%|██████    | 30/50 [04:05<02:32,  7.61s/it]

[I 2026-10-10 22:53:59,521] Trial 29 finished with value: 350.31490298016155 and parameters: {'n_estimators': 400, 'learning_rate': 0.014541613013984272, 'max_depth': 7, 'min_child_weight': 13, 'subsample': 0.7381932041681043, 'colsample_bytree': 0.8468665857952491, 'gamma': 0.09775417545967088, 'reg_alpha': 1.1848673643846149e-07, 'reg_lambda': 4.269904400432085}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  62%|██████▏   | 31/50 [04:11<02:15,  7.13s/it]

[I 2026-10-10 22:54:05,551] Trial 30 finished with value: 333.05020267220976 and parameters: {'n_estimators': 600, 'learning_rate': 0.022562257129354776, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.7061748451437128, 'colsample_bytree': 0.9820008792725654, 'gamma': 0.3876122559415767, 'reg_alpha': 4.7083689012455217e-07, 'reg_lambda': 5.636176703363136}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  64%|██████▍   | 32/50 [04:17<02:05,  6.99s/it]

[I 2026-10-10 22:54:12,217] Trial 31 finished with value: 334.0248166304414 and parameters: {'n_estimators': 700, 'learning_rate': 0.036348750615393596, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8269691747740061, 'colsample_bytree': 0.9335991131568129, 'gamma': 0.12542647119138128, 'reg_alpha': 1.4997450648729903e-06, 'reg_lambda': 3.6708014685861694}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  66%|██████▌   | 33/50 [04:29<02:22,  8.40s/it]

[I 2026-10-10 22:54:23,894] Trial 32 finished with value: 331.2845972498571 and parameters: {'n_estimators': 800, 'learning_rate': 0.04801720214609483, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8636248589247248, 'colsample_bytree': 0.9500624152402871, 'gamma': 0.2482531229470174, 'reg_alpha': 4.544327910092606e-08, 'reg_lambda': 4.418798701507015}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  68%|██████▊   | 34/50 [04:36<02:09,  8.08s/it]

[I 2026-10-10 22:54:31,227] Trial 33 finished with value: 336.99258152072133 and parameters: {'n_estimators': 700, 'learning_rate': 0.03152360964999575, 'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.7638560768453475, 'colsample_bytree': 0.8829422508946485, 'gamma': 0.4843627015085728, 'reg_alpha': 3.0436961368684465e-06, 'reg_lambda': 2.768815639422839}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  70%|███████   | 35/50 [04:43<01:53,  7.58s/it]

[I 2026-10-10 22:54:37,650] Trial 34 finished with value: 332.50019971798514 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02614189061893537, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.8282412404192374, 'colsample_bytree': 0.9201416582321027, 'gamma': 0.5538093265083176, 'reg_alpha': 7.411088142166243e-07, 'reg_lambda': 3.2082668775017305}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  72%|███████▏  | 36/50 [04:51<01:46,  7.61s/it]

[I 2026-10-10 22:54:45,312] Trial 35 finished with value: 333.21089417964714 and parameters: {'n_estimators': 700, 'learning_rate': 0.017587554077404415, 'max_depth': 7, 'min_child_weight': 11, 'subsample': 0.8973183166045675, 'colsample_bytree': 0.9422420199498915, 'gamma': 0.27747715657967476, 'reg_alpha': 1.5732869649731295e-07, 'reg_lambda': 5.126039109093055}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  74%|███████▍  | 37/50 [04:56<01:30,  6.99s/it]

[I 2026-10-10 22:54:50,860] Trial 36 finished with value: 332.2768047878154 and parameters: {'n_estimators': 500, 'learning_rate': 0.05508279860524746, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.8661484859320318, 'colsample_bytree': 0.886341495279966, 'gamma': 0.029344281269917616, 'reg_alpha': 1.5071165311181087e-05, 'reg_lambda': 1.2430412509140738}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  76%|███████▌  | 38/50 [05:03<01:23,  6.92s/it]

[I 2026-10-10 22:54:57,626] Trial 37 finished with value: 339.4307389770408 and parameters: {'n_estimators': 800, 'learning_rate': 0.04187164332018674, 'max_depth': 6, 'min_child_weight': 12, 'subsample': 0.9590967495227779, 'colsample_bytree': 0.8675392415460599, 'gamma': 0.1445522816053857, 'reg_alpha': 1.2870618938347417e-08, 'reg_lambda': 9.866850503397979}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  78%|███████▊  | 39/50 [05:09<01:12,  6.63s/it]

[I 2026-10-10 22:55:03,573] Trial 38 finished with value: 331.8207465070561 and parameters: {'n_estimators': 600, 'learning_rate': 0.026870713016582046, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.9188117193300938, 'colsample_bytree': 0.8579022294194374, 'gamma': 0.3630412731671261, 'reg_alpha': 2.0194977866056227e-06, 'reg_lambda': 3.780599432335662}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  80%|████████  | 40/50 [05:16<01:09,  6.94s/it]

[I 2026-10-10 22:55:11,246] Trial 39 finished with value: 332.6644565098592 and parameters: {'n_estimators': 1100, 'learning_rate': 0.02398779591745277, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.8090988788738462, 'colsample_bytree': 0.9121183330320529, 'gamma': 0.4443399175151308, 'reg_alpha': 4.305579555562516e-08, 'reg_lambda': 1.8729271374569272}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  82%|████████▏ | 41/50 [05:30<01:19,  8.79s/it]

[I 2026-10-10 22:55:24,359] Trial 40 finished with value: 343.70330364647356 and parameters: {'n_estimators': 900, 'learning_rate': 0.033373956600845946, 'max_depth': 8, 'min_child_weight': 13, 'subsample': 0.9068574513863148, 'colsample_bytree': 0.9629669807875978, 'gamma': 0.7841137899276869, 'reg_alpha': 4.845211480570536e-07, 'reg_lambda': 4.659017577649055}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  84%|████████▍ | 42/50 [05:31<00:53,  6.68s/it]

[I 2026-10-10 22:55:26,104] Trial 41 finished with value: 332.89998263367335 and parameters: {'n_estimators': 800, 'learning_rate': 0.04661579403868514, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.8699549059657233, 'colsample_bytree': 0.9477228970231045, 'gamma': 0.2456011037592757, 'reg_alpha': 4.165907831162822e-08, 'reg_lambda': 4.410373556032336}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  86%|████████▌ | 43/50 [05:38<00:47,  6.75s/it]

[I 2026-10-10 22:55:33,018] Trial 42 finished with value: 336.09114509683235 and parameters: {'n_estimators': 800, 'learning_rate': 0.04851034513593194, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.7852674795700879, 'colsample_bytree': 0.9804601300401858, 'gamma': 0.28969434889374474, 'reg_alpha': 1.3197494672200054e-07, 'reg_lambda': 7.4481704167124985}. Best is trial 18 with value: 329.2388238422073.

Best trial: 18. Best value: 329.239:  88%|████████▊ | 44/50 [05:45<00:40,  6.75s/it]

[I 2026-10-10 22:55:39,769] Trial 43 finished with value: 340.586947415781 and parameters: {'n_estimators': 600, 'learning_rate': 0.056427362152958745, 'max_depth': 7, 'min_child_weight': 14, 'subsample': 0.8360697419354242, 'colsample_bytree': 0.9370825238384404, 'gamma': 0.18655666217103167, 'reg_alpha': 1.1643404402812529e-08, 'reg_lambda': 6.077063155987928}. Best is trial 18 with value: 329.2388238422073.

Best trial: 44. Best value: 328.455:  90%|█████████ | 45/50 [05:47<00:26,  5.20s/it]

[I 2026-10-10 22:55:41,370] Trial 44 finished with value: 328.4553575069221 and parameters: {'n_estimators': 700, 'learning_rate': 0.04051648744937904, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.8647769360983755, 'colsample_bytree': 0.8939058520372297, 'gamma': 0.3892666261869894, 'reg_alpha': 2.7579865032847236e-08, 'reg_lambda': 3.1405487762419444}. Best is trial 44 with value: 328.4553575069221.

Best trial: 44. Best value: 328.455:  92%|█████████▏| 46/50 [05:52<00:21,  5.38s/it]

[I 2026-10-10 22:55:47,155] Trial 45 finished with value: 332.48564348705344 and parameters: {'n_estimators': 700, 'learning_rate': 0.037907640174811436, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.8946079756452463, 'colsample_bytree': 0.8886809995084015, 'gamma': 0.5043376354657544, 'reg_alpha': 2.784337655808293e-05, 'reg_lambda': 3.0924584973007816}. Best is trial 44 with value: 328.4553575069221.

Best trial: 44. Best value: 328.455:  94%|█████████▍| 47/50 [05:59<00:17,  5.79s/it]

[I 2026-10-10 22:55:53,892] Trial 46 finished with value: 329.88691244121827 and parameters: {'n_estimators': 900, 'learning_rate': 0.02674083700658463, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.7979673566017345, 'colsample_bytree': 0.9083417976436393, 'gamma': 0.40094490523925286, 'reg_alpha': 8.046695293954368e-05, 'reg_lambda': 2.5507567634628363}. Best is trial 44 with value: 328.4553575069221.

Best trial: 44. Best value: 328.455:  96%|█████████▌| 48/50 [06:11<00:15,  7.63s/it]

[I 2026-10-10 22:56:05,839] Trial 47 finished with value: 331.28539905193526 and parameters: {'n_estimators': 1100, 'learning_rate': 0.028016714619851273, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.8001753014350709, 'colsample_bytree': 0.9042443705210655, 'gamma': 0.4128786626253044, 'reg_alpha': 0.00013101567078773005, 'reg_lambda': 2.46812782124202}. Best is trial 44 with value: 328.4553575069221.

Best trial: 44. Best value: 328.455:  98%|█████████▊| 49/50 [06:13<00:05,  5.96s/it]

[I 2026-10-10 22:56:07,878] Trial 48 finished with value: 332.7240081884684 and parameters: {'n_estimators': 1100, 'learning_rate': 0.022233010501066106, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.7523405417225183, 'colsample_bytree': 0.8613542962824996, 'gamma': 0.3688708615346777, 'reg_alpha': 0.09341648778466392, 'reg_lambda': 2.603248319081422}. Best is trial 44 with value: 328.4553575069221.

Best trial: 44. Best value: 328.455: 100%|██████████| 50/50 [06:15<00:00,  7.51s/it]

[I 2026-10-10 22:56:09,675] Trial 49 finished with value: 369.6541880595971 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01482014377214011, 'max_depth': 3, 'min_child_weight': 11, 'subsample': 0.815475267376455, 'colsample_bytree': 0.8270296252985283, 'gamma': 0.3248917805475045, 'reg_alpha': 0.001345914452004509, 'reg_lambda': 1.9927148825329306}. Best is trial 44 with value: 328.4553575069221.

==========================================
BEST XGBOOST PARAMETERS
==========================================
Best RMSE:
328.4553575069221

Best Parameters:
n_estimators: 700
learning_rate: 0.04051648744937904
max_depth: 5
min_child_weight: 15
subsample: 0.8647769360983755
colsample_bytree: 0.8939058520372297
gamma: 0.3892666261869894
reg_alpha: 2.7579865032847236e-08
reg_lambda: 3.1405487762419444

In [20]:
# ============================================================
# Gradient Boosting + Optuna Hyperparameter Tuning
# ============================================================

import optuna
import numpy as np

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error


# ============================================================
# 1. Create time-based validation set
# ============================================================
# IMPORTANT:
# We only use X_tr_sc / y_tr for tuning.
# X_te_sc / y_te remains completely untouched.

val_size = int(len(X_tr_sc) * 0.20)

X_train_cv = X_tr_sc[:-val_size]
X_val_cv   = X_tr_sc[-val_size:]

y_train_cv = y_tr[:-val_size]
y_val_cv   = y_tr[-val_size:]


# ============================================================
# 2. Optuna objective function
# ============================================================

def objective(trial):

    # --------------------------------------------------------
    # Optuna will automatically search these parameters
    # --------------------------------------------------------

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            800,
            step=50
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.20,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            2,
            8
        ),

        "min_samples_split": trial.suggest_int(
            "min_samples_split",
            2,
            30
        ),

        "min_samples_leaf": trial.suggest_int(
            "min_samples_leaf",
            1,
            20
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "max_features": trial.suggest_categorical(
            "max_features",
            [None, "sqrt", "log2"]
        ),

        "loss": trial.suggest_categorical(
            "loss",
            ["squared_error", "huber"]
        )
    }


    # --------------------------------------------------------
    # Create Gradient Boosting model
    # --------------------------------------------------------

    model = GradientBoostingRegressor(
        **params,
        random_state=42
    )


    # --------------------------------------------------------
    # Train on earlier observations
    # --------------------------------------------------------

    model.fit(
        X_train_cv,
        y_train_cv
    )


    # --------------------------------------------------------
    # Predict validation period
    # --------------------------------------------------------

    pred = model.predict(X_val_cv)


    # --------------------------------------------------------
    # RMSE = Optuna objective
    # Lower RMSE is better
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(
            y_val_cv,
            pred
        )
    )

    return rmse


# ============================================================
# 3. Create Optuna study
# ============================================================

study_gb = optuna.create_study(
    direction="minimize",
    study_name="GradientBoosting_Electricity_Demand"
)


# ============================================================
# 4. Run optimization
# ============================================================

study_gb.optimize(
    objective,
    n_trials=50,
    show_progress_bar=True
)


# ============================================================
# 5. Show best result
# ============================================================

print("\n========================================")
print("BEST GRADIENT BOOSTING PARAMETERS")
print("========================================")

print("Best Validation RMSE:")
print(study_gb.best_value)

print("\nBest Parameters:")

for key, value in study_gb.best_params.items():
    print(f"{key}: {value}")

[I 2026-10-10 22:56:21,342] A new study created in memory with name: GradientBoosting_Electricity_Demand
  0%|          | 0/50 [00:00<?, ?it/s]

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?
Best trial: 0. Best value: 931.144:   2%|▏         | 1/50 [00:08<06:40,  8.17s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 22:56:29,514] Trial 0 finished with value: 931.1435851910772 and parameters: {'n_estimators': 150, 'learning_rate': 0.012229895388465278, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 19, 'subsample': 0.6320216554578926, 'max_features': 'sqrt', 'loss': 'squared_error'}. Best is trial 0 with value: 931.1435851910772.

Best trial: 1. Best value: 350.56:   4%|▍         | 2/50 [01:35<43:42, 54.64s/it] d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 22:57:56,681] Trial 1 finished with value: 350.5596328162477 and parameters: {'n_estimators': 450, 'learning_rate': 0.035402376793304755, 'max_depth': 3, 'min_samples_split': 23, 'min_samples_leaf': 5, 'subsample': 0.8975597243381914, 'max_features': None, 'loss': 'squared_error'}. Best is trial 1 with value: 350.5596328162477.

Best trial: 2. Best value: 332.781:   6%|▌         | 3/50 [04:43<1:30:35, 115.66s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:01:04,943] Trial 2 finished with value: 332.7811596148888 and parameters: {'n_estimators': 350, 'learning_rate': 0.11670261382127743, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 6, 'subsample': 0.8983255502981382, 'max_features': None, 'loss': 'huber'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:   8%|▊         | 4/50 [05:35<1:09:25, 90.56s/it] d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:01:57,041] Trial 3 finished with value: 443.522542391365 and parameters: {'n_estimators': 750, 'learning_rate': 0.19100525395168955, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 15, 'subsample': 0.6509734783525594, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  10%|█         | 5/50 [06:10<52:42, 70.28s/it]  d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:02:31,356] Trial 4 finished with value: 407.65102938006214 and parameters: {'n_estimators': 750, 'learning_rate': 0.16139857440521513, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 9, 'subsample': 0.6220528814355892, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  12%|█▏        | 6/50 [06:31<39:16, 53.55s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:02:52,430] Trial 5 finished with value: 472.4990229019497 and parameters: {'n_estimators': 250, 'learning_rate': 0.07640684608152964, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 13, 'subsample': 0.9289556523812351, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  14%|█▍        | 7/50 [06:55<31:31, 43.98s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:03:16,710] Trial 6 finished with value: 389.35535781144347 and parameters: {'n_estimators': 100, 'learning_rate': 0.12409573344022326, 'max_depth': 8, 'min_samples_split': 22, 'min_samples_leaf': 9, 'subsample': 0.7436632552788172, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  16%|█▌        | 8/50 [07:29<28:33, 40.80s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:03:50,686] Trial 7 finished with value: 422.8505667269942 and parameters: {'n_estimators': 550, 'learning_rate': 0.12067523617290703, 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 5, 'subsample': 0.9999126923384015, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  18%|█▊        | 9/50 [07:45<22:41, 33.22s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:04:07,235] Trial 8 finished with value: 616.2200797027918 and parameters: {'n_estimators': 250, 'learning_rate': 0.023789598059779652, 'max_depth': 3, 'min_samples_split': 23, 'min_samples_leaf': 2, 'subsample': 0.7930021574284702, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 2. Best value: 332.781:  20%|██        | 10/50 [08:10<20:28, 30.71s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:04:32,331] Trial 9 finished with value: 864.2027656784552 and parameters: {'n_estimators': 150, 'learning_rate': 0.011964757240012162, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 20, 'subsample': 0.6235950900474101, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 2 with value: 332.7811596148888.

Best trial: 10. Best value: 326.227:  22%|██▏       | 11/50 [12:26<1:04:39, 99.47s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:08:47,721] Trial 10 finished with value: 326.2265651533679 and parameters: {'n_estimators': 500, 'learning_rate': 0.05195960907240289, 'max_depth': 6, 'min_samples_split': 30, 'min_samples_leaf': 1, 'subsample': 0.7972478311010502, 'max_features': None, 'loss': 'huber'}. Best is trial 10 with value: 326.2265651533679.

Best trial: 11. Best value: 319.86:  24%|██▍       | 12/50 [15:56<1:24:13, 132.99s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:12:17,357] Trial 11 finished with value: 319.8602404108184 and parameters: {'n_estimators': 450, 'learning_rate': 0.054069127244056624, 'max_depth': 6, 'min_samples_split': 29, 'min_samples_leaf': 1, 'subsample': 0.8303708487171579, 'max_features': None, 'loss': 'huber'}. Best is trial 11 with value: 319.8602404108184.

Best trial: 11. Best value: 319.86:  26%|██▌       | 13/50 [19:26<1:36:29, 156.49s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:15:47,919] Trial 12 finished with value: 327.5787466241833 and parameters: {'n_estimators': 550, 'learning_rate': 0.0510291984757954, 'max_depth': 5, 'min_samples_split': 30, 'min_samples_leaf': 1, 'subsample': 0.8022626988289436, 'max_features': None, 'loss': 'huber'}. Best is trial 11 with value: 319.8602404108184.

Best trial: 11. Best value: 319.86:  28%|██▊       | 14/50 [23:33<1:50:12, 183.68s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:19:54,428] Trial 13 finished with value: 329.4536302307855 and parameters: {'n_estimators': 550, 'learning_rate': 0.05470883377413901, 'max_depth': 6, 'min_samples_split': 30, 'min_samples_leaf': 1, 'subsample': 0.8169635783561932, 'max_features': None, 'loss': 'huber'}. Best is trial 11 with value: 319.8602404108184.

Best trial: 14. Best value: 319.354:  30%|███       | 15/50 [26:37<1:47:11, 183.77s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:22:58,399] Trial 14 finished with value: 319.35380269550774 and parameters: {'n_estimators': 450, 'learning_rate': 0.0253724283420017, 'max_depth': 5, 'min_samples_split': 27, 'min_samples_leaf': 3, 'subsample': 0.7114236142016409, 'max_features': None, 'loss': 'huber'}. Best is trial 14 with value: 319.35380269550774.

Best trial: 14. Best value: 319.354:  32%|███▏      | 16/50 [28:34<1:32:53, 163.94s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:24:56,299] Trial 15 finished with value: 324.328377623472 and parameters: {'n_estimators': 400, 'learning_rate': 0.023441979665313945, 'max_depth': 5, 'min_samples_split': 26, 'min_samples_leaf': 4, 'subsample': 0.6962531278594425, 'max_features': None, 'loss': 'huber'}. Best is trial 14 with value: 319.35380269550774.

Best trial: 16. Best value: 314.546:  34%|███▍      | 17/50 [31:24<1:31:08, 165.72s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:27:46,166] Trial 16 finished with value: 314.54558084336713 and parameters: {'n_estimators': 650, 'learning_rate': 0.024023017188811304, 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 8, 'subsample': 0.743876876669379, 'max_features': None, 'loss': 'huber'}. Best is trial 16 with value: 314.54558084336713.

Best trial: 16. Best value: 314.546:  36%|███▌      | 18/50 [32:38<1:13:38, 138.09s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:28:59,926] Trial 17 finished with value: 403.7086153990843 and parameters: {'n_estimators': 650, 'learning_rate': 0.020160188943478888, 'max_depth': 2, 'min_samples_split': 16, 'min_samples_leaf': 8, 'subsample': 0.7245107172967584, 'max_features': None, 'loss': 'huber'}. Best is trial 16 with value: 314.54558084336713.

Best trial: 16. Best value: 314.546:  38%|███▊      | 19/50 [33:28<57:40, 111.62s/it]  d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:29:49,872] Trial 18 finished with value: 392.8785495089954 and parameters: {'n_estimators': 700, 'learning_rate': 0.017153854510566786, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 11, 'subsample': 0.7005195680719508, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 16 with value: 314.54558084336713.

Best trial: 16. Best value: 314.546:  40%|████      | 20/50 [35:37<58:27, 116.91s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:31:59,138] Trial 19 finished with value: 315.2145836102314 and parameters: {'n_estimators': 600, 'learning_rate': 0.03278848099256087, 'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 7, 'subsample': 0.7487850219195079, 'max_features': None, 'loss': 'huber'}. Best is trial 16 with value: 314.54558084336713.

Best trial: 20. Best value: 314.117:  42%|████▏     | 21/50 [38:08<1:01:22, 127.00s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:34:29,641] Trial 20 finished with value: 314.1166032476712 and parameters: {'n_estimators': 650, 'learning_rate': 0.03351880135252471, 'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 7, 'subsample': 0.7598252083142203, 'max_features': None, 'loss': 'huber'}. Best is trial 20 with value: 314.1166032476712.

Best trial: 20. Best value: 314.117:  44%|████▍     | 22/50 [41:45<1:11:56, 154.15s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:38:07,114] Trial 21 finished with value: 316.2622237670921 and parameters: {'n_estimators': 650, 'learning_rate': 0.03527852946554748, 'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 7, 'subsample': 0.760291978674499, 'max_features': None, 'loss': 'huber'}. Best is trial 20 with value: 314.1166032476712.

Best trial: 22. Best value: 310.096:  46%|████▌     | 23/50 [44:54<1:14:05, 164.65s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:41:16,237] Trial 22 finished with value: 310.0958906675557 and parameters: {'n_estimators': 650, 'learning_rate': 0.03384196662346916, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 11, 'subsample': 0.6709851874791144, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  48%|████▊     | 24/50 [46:17<1:00:43, 140.12s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:42:39,140] Trial 23 finished with value: 409.07861633094507 and parameters: {'n_estimators': 800, 'learning_rate': 0.015405366774998586, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 11, 'subsample': 0.6586034092894686, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  50%|█████     | 25/50 [48:26<56:57, 136.71s/it]  d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:44:47,885] Trial 24 finished with value: 312.5915512563079 and parameters: {'n_estimators': 650, 'learning_rate': 0.030510966081182207, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 11, 'subsample': 0.6755310924088239, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  52%|█████▏    | 26/50 [49:05<43:00, 107.51s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:45:27,272] Trial 25 finished with value: 374.1945866781898 and parameters: {'n_estimators': 800, 'learning_rate': 0.03862399149408404, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 15, 'subsample': 0.6778265429749398, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  54%|█████▍    | 27/50 [50:44<40:08, 104.70s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:47:05,437] Trial 26 finished with value: 320.32368025112515 and parameters: {'n_estimators': 700, 'learning_rate': 0.06930601660888185, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 11, 'subsample': 0.6011159085712022, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  56%|█████▌    | 28/50 [52:41<39:45, 108.42s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:49:02,537] Trial 27 finished with value: 315.1131626592276 and parameters: {'n_estimators': 600, 'learning_rate': 0.028568877281502817, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 13, 'subsample': 0.6619778683129012, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  58%|█████▊    | 29/50 [54:12<36:10, 103.36s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:50:34,081] Trial 28 finished with value: 355.8964623687662 and parameters: {'n_estimators': 700, 'learning_rate': 0.042291699622693066, 'max_depth': 2, 'min_samples_split': 15, 'min_samples_leaf': 13, 'subsample': 0.8482195146617545, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  60%|██████    | 30/50 [54:41<27:00, 81.02s/it] d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:51:02,987] Trial 29 finished with value: 447.67991293117353 and parameters: {'n_estimators': 600, 'learning_rate': 0.015230919383219084, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 18, 'subsample': 0.774452980787561, 'max_features': 'sqrt', 'loss': 'squared_error'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  62%|██████▏   | 31/50 [56:37<28:57, 91.46s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:52:58,809] Trial 30 finished with value: 407.70517850050845 and parameters: {'n_estimators': 750, 'learning_rate': 0.010212743406072016, 'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 10, 'subsample': 0.6777743591222678, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  64%|██████▍   | 32/50 [59:22<34:06, 113.68s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:55:44,328] Trial 31 finished with value: 313.1362462022377 and parameters: {'n_estimators': 650, 'learning_rate': 0.028074808006868547, 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 9, 'subsample': 0.7207514942650931, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  66%|██████▌   | 33/50 [1:03:23<43:00, 151.81s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-10 23:59:45,095] Trial 32 finished with value: 312.00439320551266 and parameters: {'n_estimators': 650, 'learning_rate': 0.02885799385206411, 'max_depth': 5, 'min_samples_split': 12, 'min_samples_leaf': 12, 'subsample': 0.7246099646585284, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  68%|██████▊   | 34/50 [1:07:13<46:41, 175.10s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:03:34,559] Trial 33 finished with value: 315.2482250426213 and parameters: {'n_estimators': 500, 'learning_rate': 0.019040208059330165, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 15, 'subsample': 0.6879044138124917, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  70%|███████   | 35/50 [1:11:50<51:28, 205.87s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:08:12,231] Trial 34 finished with value: 327.132067272639 and parameters: {'n_estimators': 700, 'learning_rate': 0.044395871366099626, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 12, 'subsample': 0.7204136999788748, 'max_features': None, 'loss': 'squared_error'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  72%|███████▏  | 36/50 [1:15:24<48:34, 208.19s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:11:45,816] Trial 35 finished with value: 311.6299077451728 and parameters: {'n_estimators': 600, 'learning_rate': 0.027915974309877283, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 14, 'subsample': 0.6416499233471837, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  74%|███████▍  | 37/50 [1:18:53<45:11, 208.54s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:15:15,191] Trial 36 finished with value: 310.6687885908649 and parameters: {'n_estimators': 600, 'learning_rate': 0.029975269172208323, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 14, 'subsample': 0.6352910042385063, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  76%|███████▌  | 38/50 [1:19:25<31:05, 155.49s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:15:46,878] Trial 37 finished with value: 377.98281790747467 and parameters: {'n_estimators': 500, 'learning_rate': 0.0691204947142269, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 17, 'subsample': 0.6409199554266686, 'max_features': 'sqrt', 'loss': 'squared_error'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  78%|███████▊  | 39/50 [1:21:47<27:46, 151.53s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:18:09,169] Trial 38 finished with value: 312.7196026443251 and parameters: {'n_estimators': 550, 'learning_rate': 0.02036008085261302, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 16, 'subsample': 0.6025867886450724, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  80%|████████  | 40/50 [1:22:29<19:44, 118.48s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:18:50,542] Trial 39 finished with value: 417.6224668650957 and parameters: {'n_estimators': 750, 'learning_rate': 0.08780652226387543, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 14, 'subsample': 0.6366743659304527, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  82%|████████▏ | 41/50 [1:24:24<17:36, 117.39s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:20:45,388] Trial 40 finished with value: 313.64999772905134 and parameters: {'n_estimators': 350, 'learning_rate': 0.04522501028907981, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 14, 'subsample': 0.6189002933180645, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  84%|████████▍ | 42/50 [1:28:08<19:55, 149.41s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:24:29,494] Trial 41 finished with value: 311.030470589887 and parameters: {'n_estimators': 600, 'learning_rate': 0.030088747847216768, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 12, 'subsample': 0.6581591576990534, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  86%|████████▌ | 43/50 [1:30:28<17:06, 146.66s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:26:49,755] Trial 42 finished with value: 313.37758651196884 and parameters: {'n_estimators': 600, 'learning_rate': 0.03882312935953395, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 12, 'subsample': 0.6497288656503726, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  88%|████████▊ | 44/50 [1:34:18<17:09, 171.62s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:30:39,621] Trial 43 finished with value: 313.00443360667015 and parameters: {'n_estimators': 600, 'learning_rate': 0.02767313047703991, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 14, 'subsample': 0.6191221983762865, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  90%|█████████ | 45/50 [1:35:13<11:23, 136.78s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:31:35,098] Trial 44 finished with value: 395.569714025104 and parameters: {'n_estimators': 550, 'learning_rate': 0.022078698541149754, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 16, 'subsample': 0.6619059999074292, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  92%|█████████▏| 46/50 [1:38:14<09:59, 149.92s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:34:35,664] Trial 45 finished with value: 313.84011699963725 and parameters: {'n_estimators': 500, 'learning_rate': 0.03090330282685336, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 12, 'subsample': 0.6341309753223342, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  94%|█████████▍| 47/50 [1:43:46<10:13, 204.60s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:40:07,863] Trial 46 finished with value: 311.07034906907717 and parameters: {'n_estimators': 750, 'learning_rate': 0.037124016049131195, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 10, 'subsample': 0.6669102880991468, 'max_features': None, 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  96%|█████████▌| 48/50 [1:44:59<05:30, 165.05s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:41:20,638] Trial 47 finished with value: 377.17172733183907 and parameters: {'n_estimators': 800, 'learning_rate': 0.03666726007854257, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 13, 'subsample': 0.6495889066542806, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096:  98%|█████████▊| 49/50 [1:50:54<03:41, 221.98s/it]d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

[I 2026-10-11 00:47:15,460] Trial 48 finished with value: 344.18856754196014 and parameters: {'n_estimators': 700, 'learning_rate': 0.05708161211148063, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 10, 'subsample': 0.669707269955121, 'max_features': None, 'loss': 'squared_error'}. Best is trial 22 with value: 310.0958906675557.

Best trial: 22. Best value: 310.096: 100%|██████████| 50/50 [1:52:26<00:00, 134.94s/it]

[I 2026-10-11 00:48:48,140] Trial 49 finished with value: 372.834865981844 and parameters: {'n_estimators': 750, 'learning_rate': 0.047250417135523505, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 10, 'subsample': 0.6942691405560895, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 22 with value: 310.0958906675557.

========================================
BEST GRADIENT BOOSTING PARAMETERS
========================================
Best Validation RMSE:
310.0958906675557

Best Parameters:
n_estimators: 650
learning_rate: 0.03384196662346916
max_depth: 4
min_samples_split: 11
min_samples_leaf: 11
subsample: 0.6709851874791144
max_features: None
loss: huber

In [21]:
# ============================================================
# 6. Train FINAL Gradient Boosting model
# ============================================================

best_gb_params = study_gb.best_params

m_gb = GradientBoostingRegressor(
    **best_gb_params,
    random_state=42
)


# Train on ALL training data
m_gb.fit(
    X_tr_sc,
    y_tr
)


# ============================================================
# 7. Predict on untouched test data
# ============================================================

pred_gb = m_gb.predict(X_te_sc)


# ============================================================
# 8. Evaluate using your existing metrics function
# ============================================================

results.append(
    metrics(
        "Gradient Boosting Optuna",
        y_te,
        pred_gb
    )
)


print("\nGradient Boosting testing completed.")

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

Gradient Boosting testing completed.

In [23]:
hyperparameter_summary = [
    {
        "Model": "XGBoost",
        "Search space": (
            "n_estimators∈[300, 1200] step 100; "
            "learning_rate∈[0.01, 0.10] log-scale; "
            "max_depth∈[3, 8]; "
            "min_child_weight∈[1, 15]; "
            "subsample∈[0.70, 1.0]; "
            "colsample_bytree∈[0.70, 1.0]; "
            "gamma∈[0.0, 1.0]; "
            "reg_alpha∈[1e-8, 1.0] log-scale; "
            "reg_lambda∈[1.0, 10.0] log-scale"
        ),
        "Final tuned value": study.best_params,
        "Batch size": "N/A",
        "Epochs": "N/A",
        "Optimizer": "XGBoost default optimizer",
    },
    {
        "Model": "Gradient Boosting",
        "Search space": (
            "n_estimators∈[100, 800] step 50; "
            "learning_rate∈[0.01, 0.20] log-scale; "
            "max_depth∈[2, 8]; "
            "min_samples_split∈[2, 30]; "
            "min_samples_leaf∈[1, 20]; "
            "subsample∈[0.6, 1.0]; "
            "max_features∈[None, 'sqrt', 'log2']; "
            "loss∈['squared_error', 'huber']"
        ),
        "Final tuned value": study_gb.best_params,
        "Batch size": "N/A",
        "Epochs": "N/A",
        "Optimizer": "GradientBoostingRegressor default optimizer",
    },
]

hyperparameter_table = pd.DataFrame(hyperparameter_summary)

display(hyperparameter_table)

,Model,Search space,Final tuned value,Batch size,Epochs,Optimizer
0,XGBoost,"n_estimators∈[300, 1200] step 100; learning_ra...","{'n_estimators': 700, 'learning_rate': 0.04051...",N/A,N/A,XGBoost default optimizer
1,Gradient Boosting,"n_estimators∈[100, 800] step 50; learning_rate...","{'n_estimators': 650, 'learning_rate': 0.03384...",N/A,N/A,GradientBoostingRegressor default optimizer