In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
from statsforecast.models import AutoARIMA
from statsforecast import StatsForecast

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv("D:\\Users\\Md Mahfuzur Rahman\\Desktop\\Research\\5_model\\cleaned_min_hours_23.csv", parse_dates=["datetime"])
df["unique_id"] = "BD"
df.head()

,datetime,demand_mw,load_shedding,temp_mean,wspd_mean,unique_id
0,2021-01-02 01:00:00,5834,0,13.78,3.12,BD
1,2021-01-02 02:00:00,5418,0,15.42,4.00,BD
2,2021-01-02 03:00:00,5244,0,17.17,2.78,BD
3,2021-01-02 04:00:00,5153,0,19.65,3.20,BD
4,2021-01-02 05:00:00,5154,0,21.50,2.88,BD

In [4]:
df['hour'] = df['datetime'].dt.hour

# -----------------------------
# Cyclic time features
# -----------------------------

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 23)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 23)


# -----------------------------
# Lag features
# -----------------------------

for lag in [1,23]:
    df[f'lag{lag}'] = df['demand_mw'].shift(lag)

# Remove NaN
df = df.dropna().reset_index(drop=True)

In [5]:
df_ext = (
    df[["datetime", "demand_mw",

        'hour_sin','hour_cos',
    
        'temp_mean','wspd_mean',
    
        'lag1','lag23',
    
        ]]
    .rename(columns={"datetime": "ds", "demand_mw": "y"})
    .assign(unique_id=df["unique_id"])
)

In [6]:
def metrics(name, y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float).ravel()
    y_pred = np.asarray(y_pred, dtype=float).ravel()

    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    r2   = r2_score(y_true, y_pred)
    return dict(Model=name,
                MAE=round(mae, 1),
                RMSE=round(rmse, 1),
                MAPE=round(mape, 3),
                R2=round(r2, 4))

results = []  # Store results for all models

In [7]:
df_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36524 entries, 0 to 36523
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ds         36524 non-null  datetime64[ns]
 1   y          36524 non-null  int64
 2   hour_sin   36524 non-null  float64
 3   hour_cos   36524 non-null  float64
 4   temp_mean  36524 non-null  float64
 5   wspd_mean  36524 non-null  float64
 6   lag1       36524 non-null  float64
 7   lag23      36524 non-null  float64
 8   unique_id  36524 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 2.5+ MB

In [8]:
sorted_df = df_ext.sort_values("ds").reset_index(drop=True)
test_start = sorted_df["ds"].max().to_period("M").start_time - pd.DateOffset(months=5)
train = sorted_df[sorted_df["ds"] < test_start].copy()
test = sorted_df[sorted_df["ds"] >= test_start].copy()

In [9]:
futr_exog_df = test.drop(["y"], axis=1)
futr_exog_df.head()
futr_exog_df.shape

(4117, 8)

In [10]:

# ============================================================
# 1. Different AutoARIMA configurations to test
# ============================================================

param_grid = [
    # Small search space - faster
    {
        "season_length": 23,
        "max_p": 2,
        "max_q": 2,
        "max_P": 1,
        "max_Q": 1,
        "max_order": 4,
        "approximation": True
    },

    # Medium search space
    {
        "season_length": 23,
        "max_p": 3,
        "max_q": 3,
        "max_P": 1,
        "max_Q": 1,
        "max_order": 5,
        "approximation": True
    },

    {
        "season_length": 23,
        "max_p": 4,
        "max_q": 4,
        "max_P": 2,
        "max_Q": 2,
        "max_order": 6,
        "approximation": True
    }]

# ============================================================
# 2. Time-series cross-validation
# ============================================================

results = []

for i, params in enumerate(param_grid):

    print(f"\nRunning configuration {i+1}/{len(param_grid)}")
    print(params)

    # Create AutoARIMA using current parameters
    model = AutoARIMA(
        season_length=params["season_length"],
        max_p=params["max_p"],
        max_q=params["max_q"],
        max_P=params["max_P"],
        max_Q=params["max_Q"],
        max_order=params["max_order"],
        approximation=params["approximation"],
        alias="SARIMA"
    )

    # Create StatsForecast object
    sf = StatsForecast(
        models=[model],
        freq="H"
    )

    # --------------------------------------------------------
    # Cross-validation
    #
    # h=24      -> predict next 24 hours
    # n_windows=5 -> use 5 historical validation windows
    # step_size=24 -> move forward 24 hours each time
    # --------------------------------------------------------

    cv_df = sf.cross_validation(
        df=train,
        h=23,
        n_windows=5,
        step_size=24,
        refit=True
    )

    # --------------------------------------------------------
    # Calculate RMSE
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(
            cv_df["y"],
            cv_df["SARIMA"]
        )
    )

    results.append({
        **params,
        "RMSE": rmse
    })

    print(f"RMSE = {rmse:.4f}")


# ============================================================
# 3. Show the best configuration
# ============================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "RMSE",
    ascending=True
).reset_index(drop=True)

print("\n========== BEST CONFIGURATION ==========")
print(results_df.iloc[0])

print("\n========== ALL RESULTS ==========")
print(results_df)

Running configuration 1/3
{'season_length': 23, 'max_p': 2, 'max_q': 2, 'max_P': 1, 'max_Q': 1, 'max_order': 4, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 241.6409

Running configuration 2/3
{'season_length': 23, 'max_p': 3, 'max_q': 3, 'max_P': 1, 'max_Q': 1, 'max_order': 5, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 1]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 242.0701

Running configuration 3/3
{'season_length': 23, 'max_p': 4, 'max_q': 4, 'max_P': 2, 'max_Q': 2, 'max_order': 6, 'approximation': True}

d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(
d:\Users\Md Mahfuzur Rahman\Desktop\Research\venv\Lib\site-packages\statsforecast\arima.py:672: UserWarning: possible convergence problem: minimize gave code 2]
  warnings.warn(

RMSE = 234.4570

========== BEST CONFIGURATION ==========
season_length            23
max_p                     4
max_q                     4
max_P                     2
max_Q                     2
max_order                 6
approximation          True
RMSE             234.456988
Name: 0, dtype: object

========== ALL RESULTS ==========
   season_length  max_p  max_q  max_P  max_Q  max_order  approximation  \
0             23      4      4      2      2          6           True
1             23      2      2      1      1          4           True
2             23      3      3      1      1          5           True

         RMSE
0  234.456988
1  241.640924
2  242.070058

========== BEST CONFIGURATION ==========
season_length            23
max_p                     4
max_q                     4
max_P                     2
max_Q                     2
max_order                 6
approximation          True
RMSE             234.456988
Name: 0, dtype: object

========== ALL RESULTS ==========
   season_length  max_p  max_q  max_P  max_Q  max_order  approximation  \
0             23      4      4      2      2          6           True   
1             23      2      2      1      1          4           True   
2             23      3      3      1      1          5           True   

         RMSE  
0  234.456988  
1  241.640924  
2  242.070058

In [ ]:
# Get best parameters
best = results_df.iloc[0]

print("Best parameters:")
print(best)


# ------------------------------------------------------------
# Train final model using the best configuration
# ------------------------------------------------------------

final_model = AutoARIMA(
    season_length=int(best["season_length"]),
    max_p=int(best["max_p"]),
    max_q=int(best["max_q"]),
    max_P=int(best["max_P"]),
    max_Q=int(best["max_Q"]),
    max_order=int(best["max_order"]),
    approximation=bool(best["approximation"]),
    alias="SARIMA_exog"
)

sf_final = StatsForecast(
    models=[final_model],
    freq="H"
)

sf_final.fit(df=train)

In [10]:
print("Loading data...")
df = pd.read_csv('D:\\Users\\Md Mahfuzur Rahman\\Desktop\\Research\\5_model\\cleaned_min_hours_23.csv')

df['datetime'] = pd.to_datetime(df['datetime'])
df = df.sort_values('datetime').reset_index(drop=True)

Loading data...

In [11]:
df['hour'] = df['datetime'].dt.hour

# -----------------------------
# Cyclic time features
# -----------------------------

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 23)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 23)


# -----------------------------
# Lag features
# -----------------------------

for lag in [1,23]:
    df[f'lag{lag}'] = df['demand_mw'].shift(lag)

# Remove NaN
df = df.dropna().reset_index(drop=True)

In [12]:
df.shape

(36524, 10)

In [13]:
FEATURES = [
    'hour_sin','hour_cos',

    'temp_mean','wspd_mean',

    'lag1','lag23'
]

TARGET = 'demand_mw'

In [14]:
sorted_df = df.sort_values("datetime").reset_index(drop=True)
test_start = sorted_df["datetime"].max().to_period("M").start_time - pd.DateOffset(months=5)
train = sorted_df[sorted_df["datetime"] < test_start].copy()
test = sorted_df[sorted_df["datetime"] >= test_start].copy()


# Reset indices for easier access
X_train = train[FEATURES]
X_test = test[FEATURES]
y_train = train[TARGET]
y_test = test[TARGET]

print(f"Train rows: {len(X_train):,}   Test rows: {len(X_test):,}")

Train rows: 32,407   Test rows: 4,117

In [15]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X_scaler = StandardScaler()

# Fit scaler only on training features.
X_tr_sc = X_scaler.fit_transform(X_train)
X_te_sc = X_scaler.transform(X_test)

Hyperparameter Tuning and Model Variability

I repeated the hyperparameter-tuning process several times and selected the parameter values that performed best on the validation data. However, a model trained with a different tuning run may sometimes produce slightly lower MAE, MSE, or RMSE. This can happen because some machine-learning algorithms involve randomness, and results may also vary with the data split or training conditions.


Small differences between runs are normal and do not necessarily indicate a problem. The best hyperparameters found during tuning should generally be used unchanged to train the final model. The final model’s performance should then be reported on a separate, untouched test set. I made repeated efforts to identify a strong configuration, while recognizing that small variations in results are expected.

In [16]:
import optuna
import xgboost as xgb
import numpy as np

from sklearn.metrics import mean_squared_error


# ============================================================
# 1. Create a time-based validation split
# ============================================================
# IMPORTANT:
# We use only X_tr / y_tr for Optuna.
# X_te / y_te stays completely untouched.

val_size = int(len(X_train) * 0.20)

# Works with both pandas DataFrame/Series and NumPy arrays
if hasattr(X_train, "iloc"):
    X_train_cv = X_train.iloc[:-val_size]
    X_val_cv   = X_train.iloc[-val_size:]

    y_train_cv = y_train.iloc[:-val_size]
    y_val_cv   = y_train.iloc[-val_size:]
else:
    X_train_cv = X_train[:-val_size]
    X_val_cv   = X_train[-val_size:]

    y_train_cv = y_train[:-val_size]
    y_val_cv   = y_train[-val_size:]


# ============================================================
# 2. Optuna objective function
# ============================================================

def objective(trial):

    # --------------------------------------------------------
    # Optuna chooses these hyperparameters automatically
    # --------------------------------------------------------

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 300, 1200, step=100
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate", 0.01, 0.10, log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 3, 8
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight", 1, 15
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.70, 1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.70, 1.0
        ),

        "gamma": trial.suggest_float(
            "gamma", 0.0, 1.0
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha", 1e-8, 1.0, log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda", 1.0, 10.0, log=True
        )
    }


    # --------------------------------------------------------
    # Create XGBoost model
    # --------------------------------------------------------

    model = xgb.XGBRegressor(
        objective="reg:squarederror",

        **params,

        random_state=42,
        tree_method="hist",
        n_jobs=-1
    )


    # --------------------------------------------------------
    # Train ONLY on earlier data
    # --------------------------------------------------------

    model.fit(
        X_train_cv,
        y_train_cv,
        verbose=False
    )


    # --------------------------------------------------------
    # Predict validation period
    # --------------------------------------------------------

    pred = model.predict(X_val_cv)


    # --------------------------------------------------------
    # Calculate RMSE
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(y_val_cv, pred)
    )

    return rmse


# ============================================================
# 3. Create Optuna study
# ============================================================

study = optuna.create_study(
    direction="minimize",
    study_name="XGBoost_Electricity_Demand"
)


# ============================================================
# 4. Start hyperparameter optimization
# ============================================================

study.optimize(
    objective,
    n_trials=100,       # Try 100 different combinations
    show_progress_bar=True
)


# ============================================================
# 5. Display best parameters
# ============================================================

print("\n==========================================")
print("BEST XGBOOST PARAMETERS")
print("==========================================")

print("Best RMSE:")
print(study.best_value)

print("\nBest Parameters:")
for key, value in study.best_params.items():
    print(f"{key}: {value}")

[I 2026-10-26 22:17:01,451] A new study created in memory with name: XGBoost_Electricity_Demand
Best trial: 0. Best value: 308.957:   1%|          | 1/100 [00:00<01:28,  1.12it/s]

[I 2026-10-26 22:17:02,346] Trial 0 finished with value: 308.9574960653973 and parameters: {'n_estimators': 600, 'learning_rate': 0.09511547018574512, 'max_depth': 7, 'min_child_weight': 13, 'subsample': 0.7449477394659829, 'colsample_bytree': 0.7838353398213569, 'gamma': 0.06281916471137616, 'reg_alpha': 1.839065015004247e-05, 'reg_lambda': 2.1092918004600913}. Best is trial 0 with value: 308.9574960653973.

Best trial: 0. Best value: 308.957:   2%|▏         | 2/100 [00:01<00:52,  1.85it/s]

[I 2026-10-26 22:17:02,638] Trial 1 finished with value: 402.29886278735614 and parameters: {'n_estimators': 300, 'learning_rate': 0.01497315852179502, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9850917687937629, 'colsample_bytree': 0.7130996233138838, 'gamma': 0.8703281289586459, 'reg_alpha': 4.500572053912317e-06, 'reg_lambda': 1.4062198707178852}. Best is trial 0 with value: 308.9574960653973.

Best trial: 2. Best value: 303.06:   3%|▎         | 3/100 [00:02<01:06,  1.45it/s]

[I 2026-10-26 22:17:03,502] Trial 2 finished with value: 303.060031697517 and parameters: {'n_estimators': 800, 'learning_rate': 0.07471436086095523, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.9711832842605357, 'colsample_bytree': 0.9206755891009814, 'gamma': 0.8946873069899831, 'reg_alpha': 8.545836940851333e-05, 'reg_lambda': 3.604821952944116}. Best is trial 2 with value: 303.060031697517.

Best trial: 3. Best value: 300.139:   4%|▍         | 4/100 [00:03<01:26,  1.10it/s]

[I 2026-10-26 22:17:04,742] Trial 3 finished with value: 300.13913440269664 and parameters: {'n_estimators': 700, 'learning_rate': 0.04227323797816622, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.7010548433690511, 'colsample_bytree': 0.9757665877564647, 'gamma': 0.9430273278983502, 'reg_alpha': 0.7818402517639843, 'reg_lambda': 5.029188258173134}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:   5%|▌         | 5/100 [00:04<01:39,  1.05s/it]

[I 2026-10-26 22:17:06,054] Trial 4 finished with value: 318.6692912527029 and parameters: {'n_estimators': 600, 'learning_rate': 0.057050300538632394, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7328604116098605, 'colsample_bytree': 0.8126958386780271, 'gamma': 0.3050174491221457, 'reg_alpha': 0.005792201507121319, 'reg_lambda': 1.2316827236080048}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:   6%|▌         | 6/100 [00:05<01:25,  1.09it/s]

[I 2026-10-26 22:17:06,702] Trial 5 finished with value: 315.5484436857517 and parameters: {'n_estimators': 600, 'learning_rate': 0.013116513180216352, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.9381884570450998, 'colsample_bytree': 0.8543765089937542, 'gamma': 0.29952741085493795, 'reg_alpha': 8.107176171424884e-07, 'reg_lambda': 2.96293388865951}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:   7%|▋         | 7/100 [00:08<02:23,  1.54s/it]

[I 2026-10-26 22:17:09,524] Trial 6 finished with value: 301.9401068506799 and parameters: {'n_estimators': 900, 'learning_rate': 0.04596887599117251, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.844128774366729, 'colsample_bytree': 0.96630703270586, 'gamma': 0.2924620347265957, 'reg_alpha': 0.13041194797409786, 'reg_lambda': 8.975082784487176}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:   8%|▊         | 8/100 [00:10<02:33,  1.66s/it]

[I 2026-10-26 22:17:11,451] Trial 7 finished with value: 302.0286875861298 and parameters: {'n_estimators': 700, 'learning_rate': 0.037913052775601294, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8183264436569964, 'colsample_bytree': 0.9265704615365367, 'gamma': 0.08211689759168694, 'reg_alpha': 0.0023118959667422787, 'reg_lambda': 3.7687923138303248}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:   9%|▉         | 9/100 [00:11<02:15,  1.49s/it]

[I 2026-10-26 22:17:12,575] Trial 8 finished with value: 301.6707124498499 and parameters: {'n_estimators': 900, 'learning_rate': 0.03487041561448071, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.7932492610651113, 'colsample_bytree': 0.8455061508557503, 'gamma': 0.24893303572052716, 'reg_alpha': 1.774340697821816e-07, 'reg_lambda': 1.547782494394908}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:  10%|█         | 10/100 [00:15<03:41,  2.46s/it]

[I 2026-10-26 22:17:17,200] Trial 9 finished with value: 301.2184890158637 and parameters: {'n_estimators': 1200, 'learning_rate': 0.012211504197676179, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.8198811273828408, 'colsample_bytree': 0.979341553325477, 'gamma': 0.010475387281365767, 'reg_alpha': 0.1467763015613718, 'reg_lambda': 8.035022073216144}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:  11%|█         | 11/100 [00:16<02:41,  1.82s/it]

[I 2026-10-26 22:17:17,553] Trial 10 finished with value: 387.5920858325154 and parameters: {'n_estimators': 300, 'learning_rate': 0.022717943336863108, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8786910527930276, 'colsample_bytree': 0.7088468525649639, 'gamma': 0.6623285345875733, 'reg_alpha': 0.8137052718257218, 'reg_lambda': 6.238962934142042}. Best is trial 3 with value: 300.13913440269664.

Best trial: 3. Best value: 300.139:  12%|█▏        | 12/100 [00:18<02:45,  1.88s/it]

[I 2026-10-26 22:17:19,580] Trial 11 finished with value: 300.30336224391493 and parameters: {'n_estimators': 1100, 'learning_rate': 0.010393581730625179, 'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.717035883839618, 'colsample_bytree': 0.9957501919485283, 'gamma': 0.5655663684252803, 'reg_alpha': 0.02938064302398624, 'reg_lambda': 6.063307903061458}. Best is trial 3 with value: 300.13913440269664.

Best trial: 12. Best value: 298.567:  13%|█▎        | 13/100 [00:19<02:35,  1.79s/it]

[I 2026-10-26 22:17:21,160] Trial 12 finished with value: 298.56679790710155 and parameters: {'n_estimators': 1200, 'learning_rate': 0.0252523330141981, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.7185008749394317, 'colsample_bytree': 0.9996191393037964, 'gamma': 0.6044595397858724, 'reg_alpha': 0.0053618353129860526, 'reg_lambda': 5.320066981266934}. Best is trial 12 with value: 298.56679790710155.

Best trial: 13. Best value: 298.017:  14%|█▍        | 14/100 [00:21<02:25,  1.69s/it]

[I 2026-10-26 22:17:22,616] Trial 13 finished with value: 298.0165027938889 and parameters: {'n_estimators': 1100, 'learning_rate': 0.02372600126338905, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.7007100823456116, 'colsample_bytree': 0.9300288572392023, 'gamma': 0.6988662521225605, 'reg_alpha': 0.0003828005915745899, 'reg_lambda': 4.963758988269614}. Best is trial 13 with value: 298.0165027938889.

Best trial: 14. Best value: 297.299:  15%|█▌        | 15/100 [00:22<02:10,  1.53s/it]

[I 2026-10-26 22:17:23,780] Trial 14 finished with value: 297.29853998127874 and parameters: {'n_estimators': 1100, 'learning_rate': 0.023900984550686948, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.7596397467082888, 'colsample_bytree': 0.915625877654984, 'gamma': 0.637597513551146, 'reg_alpha': 0.00044650428917942674, 'reg_lambda': 4.735697965377281}. Best is trial 14 with value: 297.29853998127874.

Best trial: 14. Best value: 297.299:  16%|█▌        | 16/100 [00:23<01:57,  1.40s/it]

[I 2026-10-26 22:17:24,869] Trial 15 finished with value: 298.7899424135625 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02001366074390149, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7675088861166629, 'colsample_bytree': 0.9102531264246041, 'gamma': 0.7485067032899657, 'reg_alpha': 0.0002666622412398883, 'reg_lambda': 2.5470663872622215}. Best is trial 14 with value: 297.29853998127874.

Best trial: 16. Best value: 297.271:  17%|█▋        | 17/100 [00:24<01:51,  1.34s/it]

[I 2026-10-26 22:17:26,078] Trial 16 finished with value: 297.2708676443085 and parameters: {'n_estimators': 1100, 'learning_rate': 0.027095362086815112, 'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.762138403174907, 'colsample_bytree': 0.8760819763165392, 'gamma': 0.4791027256792849, 'reg_alpha': 0.0003860333225968048, 'reg_lambda': 4.185429488674109}. Best is trial 16 with value: 297.2708676443085.

Best trial: 16. Best value: 297.271:  18%|█▊        | 18/100 [00:25<01:40,  1.22s/it]

[I 2026-10-26 22:17:27,020] Trial 17 finished with value: 297.65519848895633 and parameters: {'n_estimators': 1000, 'learning_rate': 0.028716249810665576, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.776989018710372, 'colsample_bytree': 0.8792140760312009, 'gamma': 0.45909617568628797, 'reg_alpha': 2.713881656629554e-05, 'reg_lambda': 3.756677014023853}. Best is trial 16 with value: 297.2708676443085.

Best trial: 16. Best value: 297.271:  19%|█▉        | 19/100 [00:26<01:35,  1.18s/it]

[I 2026-10-26 22:17:28,093] Trial 18 finished with value: 299.053402421708 and parameters: {'n_estimators': 1100, 'learning_rate': 0.01738358240871183, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.8833463277388917, 'colsample_bytree': 0.8854561112016963, 'gamma': 0.5256902261638606, 'reg_alpha': 0.0008753036668520064, 'reg_lambda': 1.9574825143602967}. Best is trial 16 with value: 297.2708676443085.

Best trial: 16. Best value: 297.271:  20%|██        | 20/100 [00:27<01:26,  1.09s/it]

[I 2026-10-26 22:17:28,966] Trial 19 finished with value: 301.86955222827623 and parameters: {'n_estimators': 1000, 'learning_rate': 0.030715166226820814, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.7634253325225756, 'colsample_bytree': 0.7755213664618198, 'gamma': 0.43220679583158594, 'reg_alpha': 2.824080911083904e-06, 'reg_lambda': 7.006745344755786}. Best is trial 16 with value: 297.2708676443085.

Best trial: 16. Best value: 297.271:  21%|██        | 21/100 [00:28<01:27,  1.10s/it]

[I 2026-10-26 22:17:30,109] Trial 20 finished with value: 299.63230070371253 and parameters: {'n_estimators': 1200, 'learning_rate': 0.05457308688848043, 'max_depth': 5, 'min_child_weight': 13, 'subsample': 0.8018525740971294, 'colsample_bytree': 0.850819470269834, 'gamma': 0.8111841152539918, 'reg_alpha': 0.00014690241943301027, 'reg_lambda': 4.170818998558024}. Best is trial 16 with value: 297.2708676443085.

Best trial: 21. Best value: 297.169:  22%|██▏       | 22/100 [00:29<01:18,  1.01s/it]

[I 2026-10-26 22:17:30,904] Trial 21 finished with value: 297.1688940022155 and parameters: {'n_estimators': 1000, 'learning_rate': 0.029049562667180638, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.7726999896721097, 'colsample_bytree': 0.8816304747697475, 'gamma': 0.453187764642515, 'reg_alpha': 2.1242893207205398e-05, 'reg_lambda': 3.069702206766452}. Best is trial 21 with value: 297.1688940022155.

Best trial: 21. Best value: 297.169:  23%|██▎       | 23/100 [00:30<01:12,  1.07it/s]

[I 2026-10-26 22:17:31,671] Trial 22 finished with value: 302.35088008388533 and parameters: {'n_estimators': 900, 'learning_rate': 0.01849356503808892, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.7459968464981236, 'colsample_bytree': 0.8893553176762705, 'gamma': 0.4117198200200226, 'reg_alpha': 2.0138662679629568e-08, 'reg_lambda': 2.9903644965576657}. Best is trial 21 with value: 297.1688940022155.

Best trial: 21. Best value: 297.169:  24%|██▍       | 24/100 [00:31<01:13,  1.03it/s]

[I 2026-10-26 22:17:32,719] Trial 23 finished with value: 297.9117423835455 and parameters: {'n_estimators': 1100, 'learning_rate': 0.029069452421377835, 'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.8484013768361846, 'colsample_bytree': 0.9478755181176989, 'gamma': 0.48451868488688266, 'reg_alpha': 3.448967238856507e-05, 'reg_lambda': 3.049414647144273}. Best is trial 21 with value: 297.1688940022155.

Best trial: 21. Best value: 297.169:  25%|██▌       | 25/100 [00:32<01:09,  1.08it/s]

[I 2026-10-26 22:17:33,543] Trial 24 finished with value: 307.14545108954485 and parameters: {'n_estimators': 1000, 'learning_rate': 0.022127075450069485, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7806909722811094, 'colsample_bytree': 0.8227695408441661, 'gamma': 0.3805655239057365, 'reg_alpha': 6.002781186108708e-06, 'reg_lambda': 4.413195365414988}. Best is trial 21 with value: 297.1688940022155.

Best trial: 21. Best value: 297.169:  26%|██▌       | 26/100 [00:32<01:01,  1.20it/s]

[I 2026-10-26 22:17:34,158] Trial 25 finished with value: 304.03430624684444 and parameters: {'n_estimators': 800, 'learning_rate': 0.032628656469293624, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.7485911013284114, 'colsample_bytree': 0.8978419750484904, 'gamma': 0.1808701017555986, 'reg_alpha': 0.0009532416050405997, 'reg_lambda': 2.3867373516134758}. Best is trial 21 with value: 297.1688940022155.

Best trial: 21. Best value: 297.169:  27%|██▋       | 27/100 [00:34<01:12,  1.01it/s]

[I 2026-10-26 22:17:35,526] Trial 26 finished with value: 299.26660354941043 and parameters: {'n_estimators': 1200, 'learning_rate': 0.015000383140541583, 'max_depth': 6, 'min_child_weight': 11, 'subsample': 0.807405766382739, 'colsample_bytree': 0.870605971539259, 'gamma': 0.6208997014997641, 'reg_alpha': 4.802687716870612e-07, 'reg_lambda': 3.2995861178606347}. Best is trial 21 with value: 297.1688940022155.

Best trial: 27. Best value: 297.066:  28%|██▊       | 28/100 [00:35<01:12,  1.01s/it]

[I 2026-10-26 22:17:36,572] Trial 27 finished with value: 297.06646457484896 and parameters: {'n_estimators': 1100, 'learning_rate': 0.026422704768297955, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8371122325054382, 'colsample_bytree': 0.9405349196212716, 'gamma': 0.5408342246775637, 'reg_alpha': 0.015503541977897245, 'reg_lambda': 4.451183376837516}. Best is trial 27 with value: 297.06646457484896.

Best trial: 27. Best value: 297.066:  29%|██▉       | 29/100 [00:35<01:07,  1.06it/s]

[I 2026-10-26 22:17:37,366] Trial 28 finished with value: 297.2155809551377 and parameters: {'n_estimators': 900, 'learning_rate': 0.047213241862406045, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.8437635971079206, 'colsample_bytree': 0.9548383800638321, 'gamma': 0.36015727772445316, 'reg_alpha': 0.020118656810282395, 'reg_lambda': 2.495965350860766}. Best is trial 27 with value: 297.06646457484896.

Best trial: 27. Best value: 297.066:  30%|███       | 30/100 [00:36<01:00,  1.16it/s]

[I 2026-10-26 22:17:38,038] Trial 29 finished with value: 299.67103056935616 and parameters: {'n_estimators': 800, 'learning_rate': 0.09111804087029678, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.8997659252509332, 'colsample_bytree': 0.9470983975257051, 'gamma': 0.36313286963276464, 'reg_alpha': 0.0274028835903959, 'reg_lambda': 1.942546258821486}. Best is trial 27 with value: 297.06646457484896.

Best trial: 30. Best value: 296.981:  31%|███       | 31/100 [00:37<00:58,  1.18it/s]

[I 2026-10-26 22:17:38,845] Trial 30 finished with value: 296.9806785592288 and parameters: {'n_estimators': 900, 'learning_rate': 0.05817724568157895, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.845955109675734, 'colsample_bytree': 0.959035864661808, 'gamma': 0.1652171687378189, 'reg_alpha': 0.021620943043085258, 'reg_lambda': 2.3629524496749497}. Best is trial 30 with value: 296.9806785592288.

Best trial: 30. Best value: 296.981:  32%|███▏      | 32/100 [00:38<00:58,  1.16it/s]

[I 2026-10-26 22:17:39,755] Trial 31 finished with value: 297.59288203433226 and parameters: {'n_estimators': 900, 'learning_rate': 0.059196697325315434, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.8453226045325671, 'colsample_bytree': 0.9495936436108265, 'gamma': 0.18732127529368636, 'reg_alpha': 0.025023478148637552, 'reg_lambda': 2.422701287385119}. Best is trial 30 with value: 296.9806785592288.

Best trial: 32. Best value: 296.575:  33%|███▎      | 33/100 [00:39<00:56,  1.18it/s]

[I 2026-10-26 22:17:40,560] Trial 32 finished with value: 296.57458484334086 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04740611945756864, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8750903818942058, 'colsample_bytree': 0.9650479832284455, 'gamma': 0.1302090408383419, 'reg_alpha': 0.1112934032463508, 'reg_lambda': 1.813139551103668}. Best is trial 32 with value: 296.57458484334086.

Best trial: 32. Best value: 296.575:  34%|███▍      | 34/100 [00:40<00:57,  1.15it/s]

[I 2026-10-26 22:17:41,479] Trial 33 finished with value: 299.733736005809 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07011494855200733, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9238070841335184, 'colsample_bytree': 0.9810725372656316, 'gamma': 0.12124904541101385, 'reg_alpha': 0.13538235514305771, 'reg_lambda': 1.6391381633103026}. Best is trial 32 with value: 296.57458484334086.

Best trial: 32. Best value: 296.575:  35%|███▌      | 35/100 [00:40<00:52,  1.25it/s]

[I 2026-10-26 22:17:42,126] Trial 34 finished with value: 302.3204529137915 and parameters: {'n_estimators': 800, 'learning_rate': 0.038241579701858694, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8682726259973003, 'colsample_bytree': 0.7402101910632242, 'gamma': 0.1729965425986958, 'reg_alpha': 0.22641525619276004, 'reg_lambda': 1.0508439206960871}. Best is trial 32 with value: 296.57458484334086.

Best trial: 32. Best value: 296.575:  36%|███▌      | 36/100 [00:41<00:50,  1.28it/s]

[I 2026-10-26 22:17:42,866] Trial 35 finished with value: 298.1452692271001 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06984290451039339, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.8983978120897664, 'colsample_bytree': 0.9347168580494525, 'gamma': 0.2355716218192636, 'reg_alpha': 0.008688812227353196, 'reg_lambda': 1.735679272420412}. Best is trial 32 with value: 296.57458484334086.

Best trial: 32. Best value: 296.575:  37%|███▋      | 37/100 [00:41<00:45,  1.39it/s]

[I 2026-10-26 22:17:43,429] Trial 36 finished with value: 303.1364946274203 and parameters: {'n_estimators': 700, 'learning_rate': 0.09707719176885782, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9534126367413969, 'colsample_bytree': 0.9650142234783963, 'gamma': 0.05709576556542395, 'reg_alpha': 0.06890428469695693, 'reg_lambda': 1.3445560418191755}. Best is trial 32 with value: 296.57458484334086.

Best trial: 32. Best value: 296.575:  38%|███▊      | 38/100 [00:42<00:39,  1.56it/s]

[I 2026-10-26 22:17:43,895] Trial 37 finished with value: 299.46346553043827 and parameters: {'n_estimators': 400, 'learning_rate': 0.05058816750802135, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.8588842554141547, 'colsample_bytree': 0.9366669310498507, 'gamma': 0.005975332320530546, 'reg_alpha': 0.4186232989377768, 'reg_lambda': 2.058399075010233}. Best is trial 32 with value: 296.57458484334086.

Best trial: 38. Best value: 296.531:  39%|███▉      | 39/100 [00:43<00:40,  1.51it/s]

[I 2026-10-26 22:17:44,611] Trial 38 finished with value: 296.5305106561549 and parameters: {'n_estimators': 800, 'learning_rate': 0.041121888130456793, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.9979970899557296, 'colsample_bytree': 0.9021222460745281, 'gamma': 0.9735455931932223, 'reg_alpha': 0.0029939563155904824, 'reg_lambda': 2.6309916921519343}. Best is trial 38 with value: 296.5305106561549.

Best trial: 38. Best value: 296.531:  40%|████      | 40/100 [00:44<00:44,  1.35it/s]

[I 2026-10-26 22:17:45,525] Trial 39 finished with value: 297.39650248027465 and parameters: {'n_estimators': 800, 'learning_rate': 0.04073328406927346, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.9699643126062868, 'colsample_bytree': 0.9129520215992398, 'gamma': 0.9387666768399738, 'reg_alpha': 0.001958834399186849, 'reg_lambda': 2.221840837119689}. Best is trial 38 with value: 296.5305106561549.

Best trial: 38. Best value: 296.531:  41%|████      | 41/100 [00:44<00:44,  1.33it/s]

[I 2026-10-26 22:17:46,300] Trial 40 finished with value: 303.10015362087825 and parameters: {'n_estimators': 500, 'learning_rate': 0.08078340591772955, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.9901329466207363, 'colsample_bytree': 0.9657483797111167, 'gamma': 0.9884379426053567, 'reg_alpha': 0.008786192371622438, 'reg_lambda': 2.702111024938532}. Best is trial 38 with value: 296.5305106561549.

Best trial: 38. Best value: 296.531:  42%|████▏     | 42/100 [00:45<00:45,  1.29it/s]

[I 2026-10-26 22:17:47,138] Trial 41 finished with value: 300.99187592857055 and parameters: {'n_estimators': 900, 'learning_rate': 0.06154255283753885, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.9233925906710863, 'colsample_bytree': 0.9028358832701013, 'gamma': 0.8255264453626949, 'reg_alpha': 0.0030810718868930927, 'reg_lambda': 3.294929965027783}. Best is trial 38 with value: 296.5305106561549.

Best trial: 38. Best value: 296.531:  43%|████▎     | 43/100 [00:46<00:40,  1.40it/s]

[I 2026-10-26 22:17:47,713] Trial 42 finished with value: 297.12897031423915 and parameters: {'n_estimators': 700, 'learning_rate': 0.04393216735931466, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.8292710046888995, 'colsample_bytree': 0.9263638471043338, 'gamma': 0.09860084043352882, 'reg_alpha': 0.06558170814230946, 'reg_lambda': 2.829950448229462}. Best is trial 38 with value: 296.5305106561549.

Best trial: 43. Best value: 296.257:  44%|████▍     | 44/100 [00:46<00:39,  1.41it/s]

[I 2026-10-26 22:17:48,405] Trial 43 finished with value: 296.2572783916034 and parameters: {'n_estimators': 700, 'learning_rate': 0.04376141440146684, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.8277159235873207, 'colsample_bytree': 0.9863963447083953, 'gamma': 0.11090920206943786, 'reg_alpha': 0.060977303600999046, 'reg_lambda': 1.8063919246309896}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  45%|████▌     | 45/100 [00:47<00:36,  1.50it/s]

[I 2026-10-26 22:17:48,967] Trial 44 finished with value: 297.8346594589018 and parameters: {'n_estimators': 600, 'learning_rate': 0.05091984739168139, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.8292739091355563, 'colsample_bytree': 0.9878814576454089, 'gamma': 0.24742863122627884, 'reg_alpha': 0.05339581561820457, 'reg_lambda': 1.4480039952990984}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  46%|████▌     | 46/100 [00:48<00:38,  1.40it/s]

[I 2026-10-26 22:17:49,798] Trial 45 finished with value: 298.7776660829922 and parameters: {'n_estimators': 700, 'learning_rate': 0.03693959882593311, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.8972128762428426, 'colsample_bytree': 0.9706480001494069, 'gamma': 0.13565411293627855, 'reg_alpha': 0.39402913070414913, 'reg_lambda': 1.8572905477004709}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  47%|████▋     | 47/100 [00:49<00:40,  1.31it/s]

[I 2026-10-26 22:17:50,685] Trial 46 finished with value: 301.8173081518023 and parameters: {'n_estimators': 800, 'learning_rate': 0.0639691606201572, 'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.8194698235746014, 'colsample_bytree': 0.9583304077159409, 'gamma': 0.06304483535393793, 'reg_alpha': 0.007722788538498905, 'reg_lambda': 1.1999421704290192}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  48%|████▊     | 48/100 [00:49<00:35,  1.47it/s]

[I 2026-10-26 22:17:51,171] Trial 47 finished with value: 297.6815884884384 and parameters: {'n_estimators': 500, 'learning_rate': 0.041401033409877656, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.860689011779753, 'colsample_bytree': 0.9862646517571376, 'gamma': 0.3330049511438407, 'reg_alpha': 0.013535525856267081, 'reg_lambda': 2.2126749123628415}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  49%|████▉     | 49/100 [00:50<00:32,  1.57it/s]

[I 2026-10-26 22:17:51,702] Trial 48 finished with value: 308.7887374484374 and parameters: {'n_estimators': 600, 'learning_rate': 0.034413798861268254, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.7893337013368312, 'colsample_bytree': 0.9376009828678185, 'gamma': 0.7260007743799647, 'reg_alpha': 0.0034420693127796935, 'reg_lambda': 1.7744954638197254}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  50%|█████     | 50/100 [00:51<00:40,  1.22it/s]

[I 2026-10-26 22:17:52,945] Trial 49 finished with value: 303.87188912434794 and parameters: {'n_estimators': 900, 'learning_rate': 0.047897019690755056, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.8305517058339503, 'colsample_bytree': 0.9981453636934893, 'gamma': 0.2849320642845853, 'reg_alpha': 0.05019692221698496, 'reg_lambda': 1.2932236087950397}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  51%|█████     | 51/100 [00:52<00:39,  1.24it/s]

[I 2026-10-26 22:17:53,720] Trial 50 finished with value: 300.04273133172217 and parameters: {'n_estimators': 700, 'learning_rate': 0.05320814694883647, 'max_depth': 6, 'min_child_weight': 11, 'subsample': 0.972609051851672, 'colsample_bytree': 0.9723354206847894, 'gamma': 0.04248529657486222, 'reg_alpha': 0.8252117166744674, 'reg_lambda': 1.4856790387014822}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  52%|█████▏    | 52/100 [00:52<00:36,  1.31it/s]

[I 2026-10-26 22:17:54,379] Trial 51 finished with value: 297.37757460003604 and parameters: {'n_estimators': 700, 'learning_rate': 0.044300713615837664, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.8313111471601682, 'colsample_bytree': 0.9248941714925066, 'gamma': 0.1143181669359775, 'reg_alpha': 0.0849110017163117, 'reg_lambda': 2.8199932477076644}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  53%|█████▎    | 53/100 [00:53<00:32,  1.43it/s]

[I 2026-10-26 22:17:54,926] Trial 52 finished with value: 297.56238841627817 and parameters: {'n_estimators': 700, 'learning_rate': 0.03969323225481282, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.9999678442944228, 'colsample_bytree': 0.9229544205494754, 'gamma': 0.2211678095395882, 'reg_alpha': 0.24863295447994307, 'reg_lambda': 2.230440744849144}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  54%|█████▍    | 54/100 [00:54<00:33,  1.39it/s]

[I 2026-10-26 22:17:55,695] Trial 53 finished with value: 297.9884252156449 and parameters: {'n_estimators': 800, 'learning_rate': 0.043185669014729956, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.8053013508366164, 'colsample_bytree': 0.9415416816786459, 'gamma': 0.14383700198940055, 'reg_alpha': 0.0016033770452024536, 'reg_lambda': 1.6650990397506895}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  55%|█████▌    | 55/100 [00:54<00:32,  1.39it/s]

[I 2026-10-26 22:17:56,417] Trial 54 finished with value: 296.3822753219227 and parameters: {'n_estimators': 900, 'learning_rate': 0.05723775221690327, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.8801686600769071, 'colsample_bytree': 0.861512894693458, 'gamma': 0.08769742148832835, 'reg_alpha': 0.041094969429501325, 'reg_lambda': 3.561206530411582}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  56%|█████▌    | 56/100 [00:55<00:33,  1.33it/s]

[I 2026-10-26 22:17:57,250] Trial 55 finished with value: 297.29705525366376 and parameters: {'n_estimators': 900, 'learning_rate': 0.05608937698202255, 'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.8726160160990046, 'colsample_bytree': 0.8630089974581304, 'gamma': 0.5612012516299089, 'reg_alpha': 0.013288214331579177, 'reg_lambda': 5.489350761532419}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  57%|█████▋    | 57/100 [00:56<00:35,  1.20it/s]

[I 2026-10-26 22:17:58,273] Trial 56 finished with value: 300.3456472341492 and parameters: {'n_estimators': 1100, 'learning_rate': 0.06798725147013526, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.8887402629126787, 'colsample_bytree': 0.8252113156196321, 'gamma': 0.040654952123251806, 'reg_alpha': 0.004099927759507894, 'reg_lambda': 3.779213802620648}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  58%|█████▊    | 58/100 [00:57<00:33,  1.24it/s]

[I 2026-10-26 22:17:59,010] Trial 57 finished with value: 298.23381137959524 and parameters: {'n_estimators': 900, 'learning_rate': 0.04941898128430256, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.8549372931734479, 'colsample_bytree': 0.841743739273149, 'gamma': 0.08557806767930597, 'reg_alpha': 0.0345877245544041, 'reg_lambda': 3.560683148066168}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  59%|█████▉    | 59/100 [00:58<00:32,  1.25it/s]

[I 2026-10-26 22:17:59,793] Trial 58 finished with value: 296.5351212335564 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05750126610110742, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.9286318815011644, 'colsample_bytree': 0.7929164332695605, 'gamma': 0.8817362986366082, 'reg_alpha': 0.17823390038960857, 'reg_lambda': 2.6277156923072806}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  60%|██████    | 60/100 [00:59<00:32,  1.24it/s]

[I 2026-10-26 22:18:00,623] Trial 59 finished with value: 298.92041426189013 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07689701477166672, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.9166319365832972, 'colsample_bytree': 0.7744382562811717, 'gamma': 0.8896221255390073, 'reg_alpha': 0.3949165611615673, 'reg_lambda': 2.607056476074847}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  61%|██████    | 61/100 [00:59<00:28,  1.39it/s]

[I 2026-10-26 22:18:01,142] Trial 60 finished with value: 299.07423566315435 and parameters: {'n_estimators': 800, 'learning_rate': 0.0870802570693027, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.9469249299071373, 'colsample_bytree': 0.8005069140221273, 'gamma': 0.9336174645444595, 'reg_alpha': 0.14241448262285086, 'reg_lambda': 3.355341977220333}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  62%|██████▏   | 62/100 [01:00<00:29,  1.31it/s]

[I 2026-10-26 22:18:02,012] Trial 61 finished with value: 298.97609122637215 and parameters: {'n_estimators': 1100, 'learning_rate': 0.06277689926870884, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.9069962009013715, 'colsample_bytree': 0.8982436317598386, 'gamma': 0.9843451673229014, 'reg_alpha': 0.09642427920594081, 'reg_lambda': 2.0374567157239847}. Best is trial 43 with value: 296.2572783916034.

Best trial: 43. Best value: 296.257:  63%|██████▎   | 63/100 [01:01<00:28,  1.30it/s]

[I 2026-10-26 22:18:02,779] Trial 62 finished with value: 297.6417860659017 and parameters: {'n_estimators': 1000, 'learning_rate': 0.057383288724644675, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.8740231270491354, 'colsample_bytree': 0.7386549514175055, 'gamma': 0.8435082238265582, 'reg_alpha': 0.041093653400706476, 'reg_lambda': 2.353772088377685}. Best is trial 43 with value: 296.2572783916034.

Best trial: 63. Best value: 296.021:  64%|██████▍   | 64/100 [01:02<00:28,  1.28it/s]

[I 2026-10-26 22:18:03,605] Trial 63 finished with value: 296.021048132561 and parameters: {'n_estimators': 900, 'learning_rate': 0.034546226850648225, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.8856156932029641, 'colsample_bytree': 0.958829289332973, 'gamma': 0.16558322714033655, 'reg_alpha': 0.016099746620075253, 'reg_lambda': 4.148108292073049}. Best is trial 63 with value: 296.021048132561.

Best trial: 63. Best value: 296.021:  65%|██████▌   | 65/100 [01:02<00:26,  1.30it/s]

[I 2026-10-26 22:18:04,333] Trial 64 finished with value: 302.3069115154333 and parameters: {'n_estimators': 900, 'learning_rate': 0.03176857061632575, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.8862955892849295, 'colsample_bytree': 0.798947773736442, 'gamma': 0.1708827678939786, 'reg_alpha': 0.0009605218596630037, 'reg_lambda': 3.828317748352804}. Best is trial 63 with value: 296.021048132561.

Best trial: 63. Best value: 296.021:  66%|██████▌   | 66/100 [01:03<00:26,  1.29it/s]

[I 2026-10-26 22:18:05,129] Trial 65 finished with value: 297.39732997288326 and parameters: {'n_estimators': 800, 'learning_rate': 0.0352457809369357, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.8651633844473139, 'colsample_bytree': 0.9602905213054527, 'gamma': 0.28850481242618264, 'reg_alpha': 0.29088570931451113, 'reg_lambda': 1.556270477857452}. Best is trial 63 with value: 296.021048132561.

Best trial: 66. Best value: 295.185:  67%|██████▋   | 67/100 [01:04<00:25,  1.31it/s]

[I 2026-10-26 22:18:05,866] Trial 66 finished with value: 295.1851511128227 and parameters: {'n_estimators': 900, 'learning_rate': 0.05290213359773378, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.9410269573932102, 'colsample_bytree': 0.9803699945868563, 'gamma': 0.7670978707868519, 'reg_alpha': 0.1911303868279449, 'reg_lambda': 1.8607399797610094}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  68%|██████▊   | 68/100 [01:05<00:25,  1.24it/s]

[I 2026-10-26 22:18:06,767] Trial 67 finished with value: 298.47560620593435 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05309940473164963, 'max_depth': 5, 'min_child_weight': 11, 'subsample': 0.9411669624981822, 'colsample_bytree': 0.9896292287137954, 'gamma': 0.7707610424790793, 'reg_alpha': 0.9865340410404025, 'reg_lambda': 1.8116496895759857}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  69%|██████▉   | 69/100 [01:06<00:24,  1.28it/s]

[I 2026-10-26 22:18:07,494] Trial 68 finished with value: 296.4828857834799 and parameters: {'n_estimators': 900, 'learning_rate': 0.04738443465007128, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.9595733697498383, 'colsample_bytree': 0.9800443476698807, 'gamma': 0.898359131492597, 'reg_alpha': 0.17836814710895507, 'reg_lambda': 5.286700121724181}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  70%|███████   | 70/100 [01:06<00:22,  1.31it/s]

[I 2026-10-26 22:18:08,215] Trial 69 finished with value: 296.2115217627431 and parameters: {'n_estimators': 800, 'learning_rate': 0.046430124289914707, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9718705678317938, 'colsample_bytree': 0.978079579604947, 'gamma': 0.9019780750079686, 'reg_alpha': 0.5389722443386419, 'reg_lambda': 6.072764827032161}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  71%|███████   | 71/100 [01:07<00:21,  1.33it/s]

[I 2026-10-26 22:18:08,948] Trial 70 finished with value: 297.34055601279823 and parameters: {'n_estimators': 800, 'learning_rate': 0.035296600905856144, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9723030311382005, 'colsample_bytree': 0.9801897531409702, 'gamma': 0.9721689188934939, 'reg_alpha': 0.44374668599983585, 'reg_lambda': 7.049165088303942}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  72%|███████▏  | 72/100 [01:08<00:22,  1.24it/s]

[I 2026-10-26 22:18:09,877] Trial 71 finished with value: 297.1858109836336 and parameters: {'n_estimators': 900, 'learning_rate': 0.04553824866542247, 'max_depth': 5, 'min_child_weight': 13, 'subsample': 0.9597338525978074, 'colsample_bytree': 0.9922099019032423, 'gamma': 0.9166747450146294, 'reg_alpha': 0.19154081681965918, 'reg_lambda': 6.630073757640749}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  73%|███████▎  | 73/100 [01:09<00:21,  1.29it/s]

[I 2026-10-26 22:18:10,589] Trial 72 finished with value: 297.4879067920241 and parameters: {'n_estimators': 800, 'learning_rate': 0.03832532715732375, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9852787195220747, 'colsample_bytree': 0.975320548351089, 'gamma': 0.878756518703034, 'reg_alpha': 0.6056091734924249, 'reg_lambda': 5.3332461562269335}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  74%|███████▍  | 74/100 [01:09<00:19,  1.33it/s]

[I 2026-10-26 22:18:11,285] Trial 73 finished with value: 295.6335490307215 and parameters: {'n_estimators': 900, 'learning_rate': 0.05303374424333301, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.9322703145964124, 'colsample_bytree': 0.999749087656056, 'gamma': 0.794039041853178, 'reg_alpha': 0.16584493035858788, 'reg_lambda': 5.789046030744555}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  75%|███████▌  | 75/100 [01:10<00:20,  1.21it/s]

[I 2026-10-26 22:18:12,284] Trial 74 finished with value: 299.68197987616804 and parameters: {'n_estimators': 900, 'learning_rate': 0.05113382602766528, 'max_depth': 6, 'min_child_weight': 15, 'subsample': 0.9644707167650196, 'colsample_bytree': 0.9791097768235463, 'gamma': 0.671556303340693, 'reg_alpha': 0.09651842446768458, 'reg_lambda': 5.865504972584312}. Best is trial 66 with value: 295.1851511128227.

Best trial: 66. Best value: 295.185:  76%|███████▌  | 76/100 [01:11<00:18,  1.30it/s]

[I 2026-10-26 22:18:12,911] Trial 75 finished with value: 295.6864893768398 and parameters: {'n_estimators': 800, 'learning_rate': 0.043188524725295746, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9328829790446249, 'colsample_bytree': 0.9957653390438915, 'gamma': 0.7896596181499759, 'reg_alpha': 0.035012870187690115, 'reg_lambda': 8.155387930425121}. Best is trial 66 with value: 295.1851511128227.

Best trial: 76. Best value: 294.497:  77%|███████▋  | 77/100 [01:12<00:17,  1.33it/s]

[I 2026-10-26 22:18:13,630] Trial 76 finished with value: 294.49700231920866 and parameters: {'n_estimators': 900, 'learning_rate': 0.046544298270924635, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9360431338203075, 'colsample_bytree': 0.9964623402528165, 'gamma': 0.7815988245334994, 'reg_alpha': 0.028289428269525713, 'reg_lambda': 9.634882746406598}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  78%|███████▊  | 78/100 [01:12<00:15,  1.39it/s]

[I 2026-10-26 22:18:14,265] Trial 77 finished with value: 299.8483210308172 and parameters: {'n_estimators': 800, 'learning_rate': 0.06651740316274164, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9390780868767105, 'colsample_bytree': 0.9978487371313718, 'gamma': 0.805131643469722, 'reg_alpha': 0.02634782329661311, 'reg_lambda': 9.973059668299713}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  79%|███████▉  | 79/100 [01:13<00:15,  1.39it/s]

[I 2026-10-26 22:18:14,993] Trial 78 finished with value: 294.9478105317956 and parameters: {'n_estimators': 900, 'learning_rate': 0.0538111956792731, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9154723112377557, 'colsample_bytree': 0.9995615098262648, 'gamma': 0.7850713579054174, 'reg_alpha': 0.006098514542345349, 'reg_lambda': 8.405013207169347}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  80%|████████  | 80/100 [01:14<00:13,  1.45it/s]

[I 2026-10-26 22:18:15,611] Trial 79 finished with value: 295.1833381561365 and parameters: {'n_estimators': 800, 'learning_rate': 0.04329825103064863, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9128874308457025, 'colsample_bytree': 0.9914555698708434, 'gamma': 0.7650590329336362, 'reg_alpha': 0.007003144731780609, 'reg_lambda': 8.0154175567389}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  81%|████████  | 81/100 [01:14<00:13,  1.46it/s]

[I 2026-10-26 22:18:16,291] Trial 80 finished with value: 296.3083144083203 and parameters: {'n_estimators': 800, 'learning_rate': 0.05295083995004102, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9129936340767538, 'colsample_bytree': 0.9980905446741257, 'gamma': 0.7749410270114471, 'reg_alpha': 0.007130014053713499, 'reg_lambda': 8.06358488240694}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  82%|████████▏ | 82/100 [01:15<00:11,  1.53it/s]

[I 2026-10-26 22:18:16,862] Trial 81 finished with value: 296.780103254076 and parameters: {'n_estimators': 700, 'learning_rate': 0.044268257351195536, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9303980577381827, 'colsample_bytree': 0.9869350837562241, 'gamma': 0.7211374157006948, 'reg_alpha': 0.012730104363725816, 'reg_lambda': 8.269479562508254}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  83%|████████▎ | 83/100 [01:16<00:14,  1.20it/s]

[I 2026-10-26 22:18:18,109] Trial 82 finished with value: 299.73631640994057 and parameters: {'n_estimators': 800, 'learning_rate': 0.0420179752822896, 'max_depth': 8, 'min_child_weight': 15, 'subsample': 0.9333914798165727, 'colsample_bytree': 0.9897538768501861, 'gamma': 0.8414875626369236, 'reg_alpha': 0.005456035657194616, 'reg_lambda': 8.833379605784888}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  84%|████████▍ | 84/100 [01:17<00:12,  1.23it/s]

[I 2026-10-26 22:18:18,877] Trial 83 finished with value: 296.01666707721034 and parameters: {'n_estimators': 900, 'learning_rate': 0.03737020573302383, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.9159719407475568, 'colsample_bytree': 0.9677666904790175, 'gamma': 0.7706855962328112, 'reg_alpha': 0.01983199277922374, 'reg_lambda': 7.385776899515814}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  85%|████████▌ | 85/100 [01:18<00:11,  1.29it/s]

[I 2026-10-26 22:18:19,565] Trial 84 finished with value: 296.2804836637067 and parameters: {'n_estimators': 900, 'learning_rate': 0.03846454462661885, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9069463913360438, 'colsample_bytree': 0.9511394707479063, 'gamma': 0.7894230500186507, 'reg_alpha': 0.023323859615031053, 'reg_lambda': 7.447078267981156}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  86%|████████▌ | 86/100 [01:18<00:10,  1.31it/s]

[I 2026-10-26 22:18:20,311] Trial 85 finished with value: 296.7816168919497 and parameters: {'n_estimators': 900, 'learning_rate': 0.032832565552145594, 'max_depth': 4, 'min_child_weight': 13, 'subsample': 0.9457446519720196, 'colsample_bytree': 0.9699222945691246, 'gamma': 0.6825588324394013, 'reg_alpha': 0.011330363301564521, 'reg_lambda': 9.991723100558973}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  87%|████████▋ | 87/100 [01:19<00:09,  1.39it/s]

[I 2026-10-26 22:18:20,917] Trial 86 finished with value: 298.41100013236775 and parameters: {'n_estimators': 900, 'learning_rate': 0.049507529872022095, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9173774055287452, 'colsample_bytree': 0.9755136624426988, 'gamma': 0.7451324470799233, 'reg_alpha': 0.018586731159565217, 'reg_lambda': 7.694686277651568}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  88%|████████▊ | 88/100 [01:20<00:08,  1.42it/s]

[I 2026-10-26 22:18:21,597] Trial 87 finished with value: 297.677573055143 and parameters: {'n_estimators': 900, 'learning_rate': 0.02987244929213013, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9510903755543998, 'colsample_bytree': 0.9614990642366732, 'gamma': 0.6427177177265442, 'reg_alpha': 0.0043686344117021625, 'reg_lambda': 8.933472320709116}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  89%|████████▉ | 89/100 [01:20<00:07,  1.39it/s]

[I 2026-10-26 22:18:22,352] Trial 88 finished with value: 295.5867443534977 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03721296033957169, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.92327362869594, 'colsample_bytree': 0.9936408063236282, 'gamma': 0.8496905190069508, 'reg_alpha': 0.0006962774372930405, 'reg_lambda': 6.761146353160655}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  90%|█████████ | 90/100 [01:21<00:07,  1.30it/s]

[I 2026-10-26 22:18:23,238] Trial 89 finished with value: 295.74910185831504 and parameters: {'n_estimators': 1000, 'learning_rate': 0.036189332285364036, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.8922835371701356, 'colsample_bytree': 0.993570403191467, 'gamma': 0.8540286450945449, 'reg_alpha': 0.00021707678320758637, 'reg_lambda': 6.786569065996878}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  91%|█████████ | 91/100 [01:22<00:07,  1.24it/s]

[I 2026-10-26 22:18:24,135] Trial 90 finished with value: 295.5065169543643 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03651942547907063, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.8939728033439871, 'colsample_bytree': 0.9996945014237599, 'gamma': 0.8546625617302378, 'reg_alpha': 0.0002758979518661014, 'reg_lambda': 6.702095271957524}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  92%|█████████▏| 92/100 [01:23<00:06,  1.24it/s]

[I 2026-10-26 22:18:24,937] Trial 91 finished with value: 296.00773321823874 and parameters: {'n_estimators': 1000, 'learning_rate': 0.040032093904920504, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9241470823732236, 'colsample_bytree': 0.9941406153972598, 'gamma': 0.8419768695397962, 'reg_alpha': 8.269126535954664e-05, 'reg_lambda': 6.557614529912944}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  93%|█████████▎| 93/100 [01:24<00:05,  1.26it/s]

[I 2026-10-26 22:18:25,693] Trial 92 finished with value: 295.8344659602731 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03636164504765053, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9060882548506202, 'colsample_bytree': 0.9990844426165246, 'gamma': 0.8495848306425847, 'reg_alpha': 6.60324655135503e-05, 'reg_lambda': 6.52221268637585}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  94%|█████████▍| 94/100 [01:25<00:04,  1.26it/s]

[I 2026-10-26 22:18:26,484] Trial 93 finished with value: 296.1711788603003 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03586927007543842, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.8943934998586174, 'colsample_bytree': 0.9971044754974607, 'gamma': 0.8101026291654515, 'reg_alpha': 0.00010018307585807434, 'reg_lambda': 9.477578499033955}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  95%|█████████▌| 95/100 [01:25<00:04,  1.21it/s]

[I 2026-10-26 22:18:27,386] Trial 94 finished with value: 296.87577631477444 and parameters: {'n_estimators': 1100, 'learning_rate': 0.031600861503650324, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.9026716205768569, 'colsample_bytree': 0.9827912235985684, 'gamma': 0.7188147611819747, 'reg_alpha': 0.0002835380431811733, 'reg_lambda': 8.258044052017866}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  96%|█████████▌| 96/100 [01:26<00:03,  1.20it/s]

[I 2026-10-26 22:18:28,237] Trial 95 finished with value: 295.80220640235257 and parameters: {'n_estimators': 1000, 'learning_rate': 0.033607285252274605, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9092251735061739, 'colsample_bytree': 0.9922194243152731, 'gamma': 0.853459705133019, 'reg_alpha': 4.6974369329753786e-05, 'reg_lambda': 6.602606580654897}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  97%|█████████▋| 97/100 [01:27<00:02,  1.21it/s]

[I 2026-10-26 22:18:29,058] Trial 96 finished with value: 296.902406629687 and parameters: {'n_estimators': 1000, 'learning_rate': 0.027170448148671457, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9112926914809892, 'colsample_bytree': 0.990977357648253, 'gamma': 0.8634971042597368, 'reg_alpha': 9.098085275678813e-06, 'reg_lambda': 8.570462584519507}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  98%|█████████▊| 98/100 [01:28<00:01,  1.18it/s]

[I 2026-10-26 22:18:29,949] Trial 97 finished with value: 295.79409804372364 and parameters: {'n_estimators': 1100, 'learning_rate': 0.028315586128139572, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9367566459925818, 'colsample_bytree': 0.9849282074267838, 'gamma': 0.8211281610150895, 'reg_alpha': 0.00019460460462831407, 'reg_lambda': 6.920105406159924}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497:  99%|█████████▉| 99/100 [01:29<00:00,  1.23it/s]

[I 2026-10-26 22:18:30,671] Trial 98 finished with value: 305.09953550030195 and parameters: {'n_estimators': 1100, 'learning_rate': 0.025526110507631032, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.9319897303511633, 'colsample_bytree': 0.9725776700742136, 'gamma': 0.7468958187034102, 'reg_alpha': 0.0002165558643329855, 'reg_lambda': 7.151723706026845}. Best is trial 76 with value: 294.49700231920866.

Best trial: 76. Best value: 294.497: 100%|██████████| 100/100 [01:30<00:00,  1.11it/s]

[I 2026-10-26 22:18:31,544] Trial 99 finished with value: 297.9651169809983 and parameters: {'n_estimators': 1100, 'learning_rate': 0.021876203053733483, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.9218914868551266, 'colsample_bytree': 0.9829593644125625, 'gamma': 0.824839781274471, 'reg_alpha': 0.0006238804275657539, 'reg_lambda': 5.728338374708165}. Best is trial 76 with value: 294.49700231920866.

==========================================
BEST XGBOOST PARAMETERS
==========================================
Best RMSE:
294.49700231920866

Best Parameters:
n_estimators: 900
learning_rate: 0.046544298270924635
max_depth: 4
min_child_weight: 14
subsample: 0.9360431338203075
colsample_bytree: 0.9964623402528165
gamma: 0.7815988245334994
reg_alpha: 0.028289428269525713
reg_lambda: 9.634882746406598

In [17]:
# ============================================================
# Gradient Boosting + Optuna Hyperparameter Tuning
# ============================================================

import optuna
import numpy as np

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error


# ============================================================
# 1. Create time-based validation set
# ============================================================
# IMPORTANT:
# We only use X_tr_sc / y_tr for tuning.
# X_te_sc / y_te remains completely untouched.

val_size = int(len(X_tr_sc) * 0.20)

X_train_cv = X_tr_sc[:-val_size]
X_val_cv   = X_tr_sc[-val_size:]

y_train_cv = y_train[:-val_size]
y_val_cv   = y_train[-val_size:]


# ============================================================
# 2. Optuna objective function
# ============================================================

def objective(trial):

    # --------------------------------------------------------
    # Optuna will automatically search these parameters
    # --------------------------------------------------------

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators",
            100,
            800,
            step=50
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.20,
            log=True
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            2,
            8
        ),

        "min_samples_split": trial.suggest_int(
            "min_samples_split",
            2,
            30
        ),

        "min_samples_leaf": trial.suggest_int(
            "min_samples_leaf",
            1,
            20
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "max_features": trial.suggest_categorical(
            "max_features",
            [None, "sqrt", "log2"]
        ),

        "loss": trial.suggest_categorical(
            "loss",
            ["squared_error", "huber"]
        )
    }


    # --------------------------------------------------------
    # Create Gradient Boosting model
    # --------------------------------------------------------

    model = GradientBoostingRegressor(
        **params,
        random_state=42
    )


    # --------------------------------------------------------
    # Train on earlier observations
    # --------------------------------------------------------

    model.fit(
        X_train_cv,
        y_train_cv
    )


    # --------------------------------------------------------
    # Predict validation period
    # --------------------------------------------------------

    pred = model.predict(X_val_cv)


    # --------------------------------------------------------
    # RMSE = Optuna objective
    # Lower RMSE is better
    # --------------------------------------------------------

    rmse = np.sqrt(
        mean_squared_error(
            y_val_cv,
            pred
        )
    )

    return rmse


# ============================================================
# 3. Create Optuna study
# ============================================================

study_gb = optuna.create_study(
    direction="minimize",
    study_name="GradientBoosting_Electricity_Demand"
)


# ============================================================
# 4. Run optimization
# ============================================================

study_gb.optimize(
    objective,
    n_trials=100,
    show_progress_bar=True
)


# ============================================================
# 5. Show best result
# ============================================================

print("\n========================================")
print("BEST GRADIENT BOOSTING PARAMETERS")
print("========================================")

print("Best Validation RMSE:")
print(study_gb.best_value)

print("\nBest Parameters:")

for key, value in study_gb.best_params.items():
    print(f"{key}: {value}")

[I 2026-10-26 22:20:48,915] A new study created in memory with name: GradientBoosting_Electricity_Demand
Best trial: 0. Best value: 302.697:   1%|          | 1/100 [00:33<55:24, 33.58s/it]

[I 2026-10-26 22:21:22,492] Trial 0 finished with value: 302.6974678033165 and parameters: {'n_estimators': 350, 'learning_rate': 0.03949054110944307, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 1, 'subsample': 0.7514067982514916, 'max_features': None, 'loss': 'huber'}. Best is trial 0 with value: 302.6974678033165.

Best trial: 0. Best value: 302.697:   2%|▏         | 2/100 [00:41<30:09, 18.47s/it]

[I 2026-10-26 22:21:30,380] Trial 1 finished with value: 307.0693098238208 and parameters: {'n_estimators': 400, 'learning_rate': 0.0980268923786642, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 18, 'subsample': 0.9888120850966, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 0 with value: 302.6974678033165.

Best trial: 2. Best value: 297.487:   3%|▎         | 3/100 [01:18<43:24, 26.85s/it]

[I 2026-10-26 22:22:07,202] Trial 2 finished with value: 297.48718846841393 and parameters: {'n_estimators': 800, 'learning_rate': 0.05396369090649155, 'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 15, 'subsample': 0.6918784771191018, 'max_features': None, 'loss': 'squared_error'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   4%|▍         | 4/100 [01:50<46:19, 28.95s/it]

[I 2026-10-26 22:22:39,378] Trial 3 finished with value: 306.69411187021876 and parameters: {'n_estimators': 550, 'learning_rate': 0.01700780225666672, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'subsample': 0.9422324152603199, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   5%|▌         | 5/100 [02:20<46:42, 29.50s/it]

[I 2026-10-26 22:23:09,844] Trial 4 finished with value: 324.67595599205015 and parameters: {'n_estimators': 600, 'learning_rate': 0.18130415213927809, 'max_depth': 8, 'min_samples_split': 22, 'min_samples_leaf': 2, 'subsample': 0.7331101227936774, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   6%|▌         | 6/100 [02:23<32:06, 20.49s/it]

[I 2026-10-26 22:23:12,858] Trial 5 finished with value: 421.16785698209316 and parameters: {'n_estimators': 200, 'learning_rate': 0.04967373375324223, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 2, 'subsample': 0.6084011827922219, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   7%|▋         | 7/100 [02:43<31:31, 20.34s/it]

[I 2026-10-26 22:23:32,869] Trial 6 finished with value: 311.06497822893374 and parameters: {'n_estimators': 800, 'learning_rate': 0.0770703863257501, 'max_depth': 7, 'min_samples_split': 29, 'min_samples_leaf': 2, 'subsample': 0.8886236743667988, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   8%|▊         | 8/100 [02:46<22:40, 14.79s/it]

[I 2026-10-26 22:23:35,773] Trial 7 finished with value: 390.2135914293703 and parameters: {'n_estimators': 300, 'learning_rate': 0.09290115381911954, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 4, 'subsample': 0.9391501946533651, 'max_features': 'sqrt', 'loss': 'squared_error'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:   9%|▉         | 9/100 [02:56<20:02, 13.21s/it]

[I 2026-10-26 22:23:45,520] Trial 8 finished with value: 314.02220237899536 and parameters: {'n_estimators': 500, 'learning_rate': 0.11118272988365423, 'max_depth': 3, 'min_samples_split': 26, 'min_samples_leaf': 17, 'subsample': 0.9178286727364399, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 2. Best value: 297.487:  10%|█         | 10/100 [03:21<25:04, 16.72s/it]

[I 2026-10-26 22:24:10,088] Trial 9 finished with value: 327.15694931327175 and parameters: {'n_estimators': 800, 'learning_rate': 0.012015156425982892, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 3, 'subsample': 0.6930894119493572, 'max_features': None, 'loss': 'huber'}. Best is trial 2 with value: 297.48718846841393.

Best trial: 10. Best value: 296.501:  11%|█         | 11/100 [03:50<30:18, 20.43s/it]

[I 2026-10-26 22:24:38,945] Trial 10 finished with value: 296.50054775100847 and parameters: {'n_estimators': 650, 'learning_rate': 0.024993069004311395, 'max_depth': 5, 'min_samples_split': 21, 'min_samples_leaf': 12, 'subsample': 0.8148080640624438, 'max_features': None, 'loss': 'squared_error'}. Best is trial 10 with value: 296.50054775100847.

Best trial: 11. Best value: 295.424:  12%|█▏        | 12/100 [04:21<34:51, 23.76s/it]

[I 2026-10-26 22:25:10,330] Trial 11 finished with value: 295.4242572822289 and parameters: {'n_estimators': 700, 'learning_rate': 0.028801115380690797, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 13, 'subsample': 0.827144911715142, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 11. Best value: 295.424:  13%|█▎        | 13/100 [04:52<37:27, 25.83s/it]

[I 2026-10-26 22:25:40,928] Trial 12 finished with value: 296.12267321218064 and parameters: {'n_estimators': 650, 'learning_rate': 0.02778730775277217, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 11, 'subsample': 0.8310677912662698, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 11. Best value: 295.424:  14%|█▍        | 14/100 [05:24<39:52, 27.82s/it]

[I 2026-10-26 22:26:13,329] Trial 13 finished with value: 296.21473483882926 and parameters: {'n_estimators': 700, 'learning_rate': 0.027670075589071877, 'max_depth': 5, 'min_samples_split': 19, 'min_samples_leaf': 10, 'subsample': 0.8377247592326331, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 11. Best value: 295.424:  15%|█▌        | 15/100 [05:50<38:46, 27.37s/it]

[I 2026-10-26 22:26:39,669] Trial 14 finished with value: 301.11843963667434 and parameters: {'n_estimators': 700, 'learning_rate': 0.02518439082559386, 'max_depth': 4, 'min_samples_split': 26, 'min_samples_leaf': 9, 'subsample': 0.8267366602219482, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 11. Best value: 295.424:  16%|█▌        | 16/100 [06:17<38:02, 27.17s/it]

[I 2026-10-26 22:27:06,376] Trial 15 finished with value: 306.1784649372281 and parameters: {'n_estimators': 500, 'learning_rate': 0.011802081507840508, 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 7, 'subsample': 0.7952066501156071, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 11. Best value: 295.424:  17%|█▋        | 17/100 [06:45<38:02, 27.50s/it]

[I 2026-10-26 22:27:34,643] Trial 16 finished with value: 305.0504681248124 and parameters: {'n_estimators': 700, 'learning_rate': 0.01785334941196636, 'max_depth': 4, 'min_samples_split': 24, 'min_samples_leaf': 14, 'subsample': 0.8758459853394557, 'max_features': None, 'loss': 'squared_error'}. Best is trial 11 with value: 295.4242572822289.

Best trial: 17. Best value: 294.711:  18%|█▊        | 18/100 [07:17<39:08, 28.64s/it]

[I 2026-10-26 22:28:05,918] Trial 17 finished with value: 294.7112601827965 and parameters: {'n_estimators': 600, 'learning_rate': 0.0365386533130621, 'max_depth': 6, 'min_samples_split': 29, 'min_samples_leaf': 20, 'subsample': 0.7648915657255206, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  19%|█▉        | 19/100 [07:22<29:08, 21.59s/it]

[I 2026-10-26 22:28:11,091] Trial 18 finished with value: 320.0459453740522 and parameters: {'n_estimators': 100, 'learning_rate': 0.04235331419727898, 'max_depth': 6, 'min_samples_split': 30, 'min_samples_leaf': 20, 'subsample': 0.757464068047658, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  20%|██        | 20/100 [07:31<23:41, 17.77s/it]

[I 2026-10-26 22:28:19,977] Trial 19 finished with value: 309.33239084141456 and parameters: {'n_estimators': 450, 'learning_rate': 0.01949784234856364, 'max_depth': 7, 'min_samples_split': 27, 'min_samples_leaf': 19, 'subsample': 0.6133726776017665, 'max_features': 'sqrt', 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  21%|██        | 21/100 [07:50<23:56, 18.19s/it]

[I 2026-10-26 22:28:39,133] Trial 20 finished with value: 297.12946325769934 and parameters: {'n_estimators': 600, 'learning_rate': 0.06404154176885263, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 15, 'subsample': 0.6692896472229626, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  22%|██▏       | 22/100 [08:21<28:47, 22.15s/it]

[I 2026-10-26 22:29:10,512] Trial 21 finished with value: 297.59812345191676 and parameters: {'n_estimators': 650, 'learning_rate': 0.03632799159893947, 'max_depth': 5, 'min_samples_split': 22, 'min_samples_leaf': 6, 'subsample': 0.8584434617258644, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  23%|██▎       | 23/100 [08:53<32:22, 25.22s/it]

[I 2026-10-26 22:29:42,908] Trial 22 finished with value: 295.6650683856726 and parameters: {'n_estimators': 600, 'learning_rate': 0.03023438492217957, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 11, 'subsample': 0.7866868745764681, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  24%|██▍       | 24/100 [09:21<32:46, 25.87s/it]

[I 2026-10-26 22:30:10,293] Trial 23 finished with value: 294.9450867784793 and parameters: {'n_estimators': 550, 'learning_rate': 0.03181007362893813, 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 12, 'subsample': 0.7761250253941635, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  25%|██▌       | 25/100 [09:50<33:37, 26.90s/it]

[I 2026-10-26 22:30:39,600] Trial 24 finished with value: 295.2365260682347 and parameters: {'n_estimators': 500, 'learning_rate': 0.03443805788186, 'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 13, 'subsample': 0.7755429382647385, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  26%|██▌       | 26/100 [10:17<33:12, 26.92s/it]

[I 2026-10-26 22:31:06,573] Trial 25 finished with value: 296.7436906049979 and parameters: {'n_estimators': 450, 'learning_rate': 0.05402588235738409, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 16, 'subsample': 0.7680940751966765, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  27%|██▋       | 27/100 [10:49<34:38, 28.48s/it]

[I 2026-10-26 22:31:38,669] Trial 26 finished with value: 298.3902615988614 and parameters: {'n_estimators': 500, 'learning_rate': 0.036475450512248375, 'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 8, 'subsample': 0.7233520781691918, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  28%|██▊       | 28/100 [11:05<29:42, 24.75s/it]

[I 2026-10-26 22:31:54,738] Trial 27 finished with value: 300.1577679031003 and parameters: {'n_estimators': 300, 'learning_rate': 0.020317300807920328, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 13, 'subsample': 0.6466284239639191, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  29%|██▉       | 29/100 [11:16<24:22, 20.59s/it]

[I 2026-10-26 22:32:05,621] Trial 28 finished with value: 325.7788158156278 and parameters: {'n_estimators': 550, 'learning_rate': 0.014676675721789205, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 20, 'subsample': 0.7156311093858452, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  30%|███       | 30/100 [11:38<24:34, 21.06s/it]

[I 2026-10-26 22:32:27,768] Trial 29 finished with value: 298.0757700484418 and parameters: {'n_estimators': 350, 'learning_rate': 0.04069096465538021, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 17, 'subsample': 0.7910828476749704, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  31%|███       | 31/100 [11:59<24:03, 20.92s/it]

[I 2026-10-26 22:32:48,379] Trial 30 finished with value: 299.3066980319065 and parameters: {'n_estimators': 400, 'learning_rate': 0.06837296912472293, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 6, 'subsample': 0.7498241502166331, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  32%|███▏      | 32/100 [12:45<32:22, 28.57s/it]

[I 2026-10-26 22:33:34,800] Trial 31 finished with value: 295.2608172132693 and parameters: {'n_estimators': 750, 'learning_rate': 0.033179977015422676, 'max_depth': 7, 'min_samples_split': 24, 'min_samples_leaf': 13, 'subsample': 0.7750837140631273, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  33%|███▎      | 33/100 [13:30<37:25, 33.51s/it]

[I 2026-10-26 22:34:19,832] Trial 32 finished with value: 296.36870303815164 and parameters: {'n_estimators': 750, 'learning_rate': 0.034437012899904994, 'max_depth': 7, 'min_samples_split': 28, 'min_samples_leaf': 13, 'subsample': 0.7813741213651944, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  34%|███▍      | 34/100 [14:05<37:15, 33.88s/it]

[I 2026-10-26 22:34:54,567] Trial 33 finished with value: 297.01103186233144 and parameters: {'n_estimators': 550, 'learning_rate': 0.04656768871491121, 'max_depth': 8, 'min_samples_split': 24, 'min_samples_leaf': 15, 'subsample': 0.7506929121445485, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  35%|███▌      | 35/100 [14:26<32:29, 29.99s/it]

[I 2026-10-26 22:35:15,480] Trial 34 finished with value: 298.2135518071201 and parameters: {'n_estimators': 450, 'learning_rate': 0.021902350702016675, 'max_depth': 6, 'min_samples_split': 25, 'min_samples_leaf': 18, 'subsample': 0.7053121917418129, 'max_features': None, 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 17. Best value: 294.711:  36%|███▌      | 36/100 [14:43<27:54, 26.16s/it]

[I 2026-10-26 22:35:32,722] Trial 35 finished with value: 300.25837694781495 and parameters: {'n_estimators': 750, 'learning_rate': 0.032747965895965035, 'max_depth': 7, 'min_samples_split': 30, 'min_samples_leaf': 11, 'subsample': 0.8059293076938618, 'max_features': 'log2', 'loss': 'squared_error'}. Best is trial 17 with value: 294.7112601827965.

Best trial: 36. Best value: 291.109:  37%|███▋      | 37/100 [15:25<32:14, 30.71s/it]

[I 2026-10-26 22:36:14,048] Trial 36 finished with value: 291.1089129887531 and parameters: {'n_estimators': 550, 'learning_rate': 0.05594714222852332, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 9, 'subsample': 0.7413047407714715, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  38%|███▊      | 38/100 [15:43<27:54, 27.01s/it]

[I 2026-10-26 22:36:32,421] Trial 37 finished with value: 297.775368685853 and parameters: {'n_estimators': 550, 'learning_rate': 0.05526894848913489, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 9, 'subsample': 0.7387010551304605, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  39%|███▉      | 39/100 [16:34<34:55, 34.35s/it]

[I 2026-10-26 22:37:23,895] Trial 38 finished with value: 305.5267157979252 and parameters: {'n_estimators': 600, 'learning_rate': 0.1462303624599884, 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 8, 'subsample': 0.6703940324040545, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  40%|████      | 40/100 [16:56<30:34, 30.58s/it]

[I 2026-10-26 22:37:45,665] Trial 39 finished with value: 298.49521124310024 and parameters: {'n_estimators': 400, 'learning_rate': 0.06201179725993926, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 6, 'subsample': 0.9963116929699702, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  41%|████      | 41/100 [17:27<30:14, 30.75s/it]

[I 2026-10-26 22:38:16,824] Trial 40 finished with value: 292.294895251277 and parameters: {'n_estimators': 500, 'learning_rate': 0.08918908879191956, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 10, 'subsample': 0.7326669064055099, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  42%|████▏     | 42/100 [17:58<29:48, 30.84s/it]

[I 2026-10-26 22:38:47,865] Trial 41 finished with value: 291.54180008565584 and parameters: {'n_estimators': 500, 'learning_rate': 0.09429728368222873, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 9, 'subsample': 0.7396456932537485, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  43%|████▎     | 43/100 [18:34<30:34, 32.19s/it]

[I 2026-10-26 22:39:23,212] Trial 42 finished with value: 291.5142717545712 and parameters: {'n_estimators': 550, 'learning_rate': 0.08750023721400256, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 10, 'subsample': 0.7253340261146451, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 36. Best value: 291.109:  44%|████▍     | 44/100 [19:06<29:56, 32.09s/it]

[I 2026-10-26 22:39:55,054] Trial 43 finished with value: 293.37508145522054 and parameters: {'n_estimators': 500, 'learning_rate': 0.0910452036998371, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4, 'subsample': 0.6830921342639632, 'max_features': None, 'loss': 'huber'}. Best is trial 36 with value: 291.1089129887531.

Best trial: 44. Best value: 290.243:  45%|████▌     | 45/100 [19:26<26:13, 28.60s/it]

[I 2026-10-26 22:40:15,535] Trial 44 finished with value: 290.2431471011942 and parameters: {'n_estimators': 400, 'learning_rate': 0.09787926624540631, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'subsample': 0.6821767520650998, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  46%|████▌     | 46/100 [19:37<20:52, 23.19s/it]

[I 2026-10-26 22:40:26,083] Trial 45 finished with value: 302.8461009210565 and parameters: {'n_estimators': 400, 'learning_rate': 0.12038206800660886, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 10, 'subsample': 0.642760893142853, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  47%|████▋     | 47/100 [19:55<19:11, 21.73s/it]

[I 2026-10-26 22:40:44,422] Trial 46 finished with value: 292.2818368424479 and parameters: {'n_estimators': 350, 'learning_rate': 0.07789694553244021, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'subsample': 0.6990506104652798, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  48%|████▊     | 48/100 [20:10<16:59, 19.60s/it]

[I 2026-10-26 22:40:59,042] Trial 47 finished with value: 292.0891699950365 and parameters: {'n_estimators': 350, 'learning_rate': 0.07461542173163575, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'subsample': 0.7038364941545654, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  49%|████▉     | 49/100 [20:16<13:19, 15.69s/it]

[I 2026-10-26 22:41:05,596] Trial 48 finished with value: 306.66823537831783 and parameters: {'n_estimators': 300, 'learning_rate': 0.1135154793871199, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 5, 'subsample': 0.6482563724770904, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  50%|█████     | 50/100 [20:21<10:19, 12.38s/it]

[I 2026-10-26 22:41:10,264] Trial 49 finished with value: 331.4803585858577 and parameters: {'n_estimators': 200, 'learning_rate': 0.1398648713430597, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 1, 'subsample': 0.7098131345167635, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  51%|█████     | 51/100 [20:29<09:02, 11.08s/it]

[I 2026-10-26 22:41:18,295] Trial 50 finished with value: 305.41442007650824 and parameters: {'n_estimators': 250, 'learning_rate': 0.0794848445349253, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 3, 'subsample': 0.6767234986692795, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  52%|█████▏    | 52/100 [20:47<10:33, 13.21s/it]

[I 2026-10-26 22:41:36,474] Trial 51 finished with value: 291.96566554525725 and parameters: {'n_estimators': 350, 'learning_rate': 0.07771073384923176, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'subsample': 0.7040065393604887, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  53%|█████▎    | 53/100 [21:02<10:41, 13.65s/it]

[I 2026-10-26 22:41:51,165] Trial 52 finished with value: 291.7167208041543 and parameters: {'n_estimators': 350, 'learning_rate': 0.10376502932761714, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 3, 'subsample': 0.7285554852535583, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  54%|█████▍    | 54/100 [21:26<12:52, 16.80s/it]

[I 2026-10-26 22:42:15,297] Trial 53 finished with value: 292.1663366427106 and parameters: {'n_estimators': 450, 'learning_rate': 0.10087523643802698, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'subsample': 0.7330039608678218, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  55%|█████▌    | 55/100 [21:39<11:49, 15.77s/it]

[I 2026-10-26 22:42:28,659] Trial 54 finished with value: 292.529706815038 and parameters: {'n_estimators': 250, 'learning_rate': 0.1323881685921066, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 7, 'subsample': 0.6901241837253128, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  56%|█████▌    | 56/100 [21:55<11:36, 15.83s/it]

[I 2026-10-26 22:42:44,638] Trial 55 finished with value: 297.1981864606069 and parameters: {'n_estimators': 400, 'learning_rate': 0.17567505182613144, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3, 'subsample': 0.7225504164693963, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  57%|█████▋    | 57/100 [22:06<10:20, 14.44s/it]

[I 2026-10-26 22:42:55,828] Trial 56 finished with value: 290.53305776621585 and parameters: {'n_estimators': 250, 'learning_rate': 0.10193071428800793, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5, 'subsample': 0.6236454711886852, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  58%|█████▊    | 58/100 [22:10<07:48, 11.16s/it]

[I 2026-10-26 22:42:59,334] Trial 57 finished with value: 312.179967139912 and parameters: {'n_estimators': 100, 'learning_rate': 0.10151193605119888, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 5, 'subsample': 0.6003471543544171, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  59%|█████▉    | 59/100 [22:17<06:51, 10.04s/it]

[I 2026-10-26 22:43:06,756] Trial 58 finished with value: 298.35505397449515 and parameters: {'n_estimators': 250, 'learning_rate': 0.17417818825592712, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 8, 'subsample': 0.655783977213289, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  60%|██████    | 60/100 [22:21<05:28,  8.22s/it]

[I 2026-10-26 22:43:10,743] Trial 59 finished with value: 312.0489652421032 and parameters: {'n_estimators': 150, 'learning_rate': 0.1530673639011792, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 7, 'subsample': 0.6264830616561653, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 44. Best value: 290.243:  61%|██████    | 61/100 [22:32<05:52,  9.03s/it]

[I 2026-10-26 22:43:21,670] Trial 60 finished with value: 296.5014590529713 and parameters: {'n_estimators': 200, 'learning_rate': 0.12427732835207092, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'subsample': 0.9641724840734103, 'max_features': None, 'loss': 'huber'}. Best is trial 44 with value: 290.2431471011942.

Best trial: 61. Best value: 289.47:  62%|██████▏   | 62/100 [22:47<06:53, 10.87s/it]

[I 2026-10-26 22:43:36,839] Trial 61 finished with value: 289.47005319126635 and parameters: {'n_estimators': 300, 'learning_rate': 0.08258528167237551, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'subsample': 0.6304290908263516, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  63%|██████▎   | 63/100 [23:02<07:28, 12.12s/it]

[I 2026-10-26 22:43:51,860] Trial 62 finished with value: 292.87084515449226 and parameters: {'n_estimators': 300, 'learning_rate': 0.08658514801100278, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 3, 'subsample': 0.628528082397414, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  64%|██████▍   | 64/100 [23:21<08:20, 13.91s/it]

[I 2026-10-26 22:44:09,937] Trial 63 finished with value: 292.80048456101923 and parameters: {'n_estimators': 300, 'learning_rate': 0.10671305181990443, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'subsample': 0.6606387809525839, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  65%|██████▌   | 65/100 [23:32<07:45, 13.31s/it]

[I 2026-10-26 22:44:21,867] Trial 64 finished with value: 291.55957195272674 and parameters: {'n_estimators': 250, 'learning_rate': 0.06049730950750084, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 9, 'subsample': 0.6293950352509332, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  66%|██████▌   | 66/100 [23:42<06:50, 12.06s/it]

[I 2026-10-26 22:44:31,009] Trial 65 finished with value: 293.1828785571766 and parameters: {'n_estimators': 200, 'learning_rate': 0.06726193548524019, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 9, 'subsample': 0.6116632727462469, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  67%|██████▋   | 67/100 [23:45<05:16,  9.59s/it]

[I 2026-10-26 22:44:34,819] Trial 66 finished with value: 357.2783689734139 and parameters: {'n_estimators': 150, 'learning_rate': 0.04539980507096565, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 11, 'subsample': 0.6336355142210541, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  68%|██████▊   | 68/100 [23:57<05:27, 10.25s/it]

[I 2026-10-26 22:44:46,604] Trial 67 finished with value: 292.78841342131835 and parameters: {'n_estimators': 250, 'learning_rate': 0.05749294675108397, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 9, 'subsample': 0.6153025711991708, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 61. Best value: 289.47:  69%|██████▉   | 69/100 [24:23<07:43, 14.94s/it]

[I 2026-10-26 22:45:12,512] Trial 68 finished with value: 289.61300312735057 and parameters: {'n_estimators': 450, 'learning_rate': 0.07105635265565405, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 10, 'subsample': 0.6343525979015765, 'max_features': None, 'loss': 'huber'}. Best is trial 61 with value: 289.47005319126635.

Best trial: 69. Best value: 288.207:  70%|███████   | 70/100 [24:53<09:39, 19.33s/it]

[I 2026-10-26 22:45:42,070] Trial 69 finished with value: 288.20737233298195 and parameters: {'n_estimators': 450, 'learning_rate': 0.06911732876051693, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 12, 'subsample': 0.6863169479272837, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  71%|███████   | 71/100 [25:20<10:27, 21.63s/it]

[I 2026-10-26 22:46:09,064] Trial 70 finished with value: 290.5749260479283 and parameters: {'n_estimators': 450, 'learning_rate': 0.07050895077026592, 'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 12, 'subsample': 0.6562482988804319, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  72%|███████▏  | 72/100 [25:48<11:04, 23.74s/it]

[I 2026-10-26 22:46:37,714] Trial 71 finished with value: 290.0648375125475 and parameters: {'n_estimators': 450, 'learning_rate': 0.07085369841003848, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 12, 'subsample': 0.6612753215406636, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  73%|███████▎  | 73/100 [26:16<11:12, 24.89s/it]

[I 2026-10-26 22:47:05,304] Trial 72 finished with value: 290.70865823901124 and parameters: {'n_estimators': 450, 'learning_rate': 0.050457705187761756, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 12, 'subsample': 0.6608782273879628, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  74%|███████▍  | 74/100 [26:43<11:03, 25.51s/it]

[I 2026-10-26 22:47:32,274] Trial 73 finished with value: 290.9685580131652 and parameters: {'n_estimators': 450, 'learning_rate': 0.07047249137822563, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 12, 'subsample': 0.6616253033562243, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  75%|███████▌  | 75/100 [27:07<10:26, 25.06s/it]

[I 2026-10-26 22:47:56,272] Trial 74 finished with value: 290.5483128822483 and parameters: {'n_estimators': 400, 'learning_rate': 0.0497110221685604, 'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 14, 'subsample': 0.640986980251475, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  76%|███████▌  | 76/100 [27:31<09:55, 24.82s/it]

[I 2026-10-26 22:48:20,522] Trial 75 finished with value: 289.310792840193 and parameters: {'n_estimators': 400, 'learning_rate': 0.050001138097658375, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 14, 'subsample': 0.63719492206089, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  77%|███████▋  | 77/100 [27:55<09:24, 24.56s/it]

[I 2026-10-26 22:48:44,485] Trial 76 finished with value: 290.3098266439857 and parameters: {'n_estimators': 400, 'learning_rate': 0.04863563734768228, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 14, 'subsample': 0.640921257482867, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  78%|███████▊  | 78/100 [28:08<07:42, 21.04s/it]

[I 2026-10-26 22:48:57,307] Trial 77 finished with value: 299.91265996132205 and parameters: {'n_estimators': 400, 'learning_rate': 0.08213394120940154, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 16, 'subsample': 0.6181882822234398, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  79%|███████▉  | 79/100 [28:24<06:52, 19.64s/it]

[I 2026-10-26 22:49:13,690] Trial 78 finished with value: 292.2080853144303 and parameters: {'n_estimators': 350, 'learning_rate': 0.0431317305587574, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 14, 'subsample': 0.6019150715200016, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  80%|████████  | 80/100 [28:38<05:55, 17.80s/it]

[I 2026-10-26 22:49:27,177] Trial 79 finished with value: 300.73634428660233 and parameters: {'n_estimators': 400, 'learning_rate': 0.0616798118726333, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 15, 'subsample': 0.6816747811516547, 'max_features': 'log2', 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  81%|████████  | 81/100 [29:15<07:28, 23.59s/it]

[I 2026-10-26 22:50:04,302] Trial 80 finished with value: 292.5827709980066 and parameters: {'n_estimators': 500, 'learning_rate': 0.05147117593346352, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 14, 'subsample': 0.6695848475700182, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  82%|████████▏ | 82/100 [29:39<07:05, 23.63s/it]

[I 2026-10-26 22:50:28,015] Trial 81 finished with value: 289.48833148788725 and parameters: {'n_estimators': 400, 'learning_rate': 0.048167992817886, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 14, 'subsample': 0.6375978328708183, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  83%|████████▎ | 83/100 [30:06<06:59, 24.69s/it]

[I 2026-10-26 22:50:55,189] Trial 82 finished with value: 290.05328752163376 and parameters: {'n_estimators': 450, 'learning_rate': 0.07230705503373026, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 15, 'subsample': 0.6355858175212271, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  84%|████████▍ | 84/100 [30:33<06:46, 25.38s/it]

[I 2026-10-26 22:51:22,160] Trial 83 finished with value: 290.2499048247554 and parameters: {'n_estimators': 450, 'learning_rate': 0.038890237015128046, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 16, 'subsample': 0.6380428603196878, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  85%|████████▌ | 85/100 [30:59<06:25, 25.72s/it]

[I 2026-10-26 22:51:48,685] Trial 84 finished with value: 289.70629144293184 and parameters: {'n_estimators': 450, 'learning_rate': 0.06413649922778476, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 16, 'subsample': 0.651122504274591, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  86%|████████▌ | 86/100 [31:33<06:32, 28.05s/it]

[I 2026-10-26 22:52:22,158] Trial 85 finished with value: 291.32093740497317 and parameters: {'n_estimators': 450, 'learning_rate': 0.06572051831361686, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 17, 'subsample': 0.6897344967393515, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  87%|████████▋ | 87/100 [31:59<05:56, 27.41s/it]

[I 2026-10-26 22:52:48,084] Trial 86 finished with value: 291.2798785932369 and parameters: {'n_estimators': 450, 'learning_rate': 0.07417786468956734, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 15, 'subsample': 0.6478672849474435, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  88%|████████▊ | 88/100 [32:28<05:36, 28.04s/it]

[I 2026-10-26 22:53:17,598] Trial 87 finished with value: 289.19122446393044 and parameters: {'n_estimators': 500, 'learning_rate': 0.06018957999804786, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 18, 'subsample': 0.6521829752647623, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  89%|████████▉ | 89/100 [32:56<05:08, 28.06s/it]

[I 2026-10-26 22:53:45,686] Trial 88 finished with value: 290.2472129822767 and parameters: {'n_estimators': 500, 'learning_rate': 0.05811561158403463, 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 19, 'subsample': 0.6517090006983361, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  90%|█████████ | 90/100 [33:31<05:00, 30.00s/it]

[I 2026-10-26 22:54:20,226] Trial 89 finished with value: 291.96705925161865 and parameters: {'n_estimators': 500, 'learning_rate': 0.06357350007458294, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 17, 'subsample': 0.672332085817531, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  91%|█████████ | 91/100 [34:01<04:30, 30.04s/it]

[I 2026-10-26 22:54:50,360] Trial 90 finished with value: 312.29163785489993 and parameters: {'n_estimators': 500, 'learning_rate': 0.010084477747755678, 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 18, 'subsample': 0.6228777243782034, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  92%|█████████▏| 92/100 [34:25<03:45, 28.16s/it]

[I 2026-10-26 22:55:14,129] Trial 91 finished with value: 290.2522762005834 and parameters: {'n_estimators': 400, 'learning_rate': 0.08290089939356336, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 13, 'subsample': 0.6825554208364162, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  93%|█████████▎| 93/100 [34:51<03:12, 27.55s/it]

[I 2026-10-26 22:55:40,261] Trial 92 finished with value: 290.2538961725716 and parameters: {'n_estimators': 450, 'learning_rate': 0.07386098125872526, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 16, 'subsample': 0.6652150329671646, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  94%|█████████▍| 94/100 [35:10<02:30, 25.01s/it]

[I 2026-10-26 22:55:59,338] Trial 93 finished with value: 289.7048863428748 and parameters: {'n_estimators': 350, 'learning_rate': 0.0534294019456289, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 19, 'subsample': 0.6078468572297729, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  95%|█████████▌| 95/100 [35:30<01:57, 23.43s/it]

[I 2026-10-26 22:56:19,069] Trial 94 finished with value: 290.3948463841344 and parameters: {'n_estimators': 350, 'learning_rate': 0.05266325207288839, 'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 19, 'subsample': 0.638031703651524, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  96%|█████████▌| 96/100 [35:49<01:28, 22.16s/it]

[I 2026-10-26 22:56:38,265] Trial 95 finished with value: 289.7915165195704 and parameters: {'n_estimators': 350, 'learning_rate': 0.04469308817263021, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 18, 'subsample': 0.6065993650402062, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  97%|█████████▋| 97/100 [36:08<01:04, 21.36s/it]

[I 2026-10-26 22:56:57,768] Trial 96 finished with value: 291.10439319294136 and parameters: {'n_estimators': 350, 'learning_rate': 0.03912933624601052, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 18, 'subsample': 0.6058738584162814, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  98%|█████████▊| 98/100 [36:21<00:37, 18.65s/it]

[I 2026-10-26 22:57:10,094] Trial 97 finished with value: 299.9456344029787 and parameters: {'n_estimators': 300, 'learning_rate': 0.04519371633278626, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 15, 'subsample': 0.6106203919527827, 'max_features': 'sqrt', 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207:  99%|█████████▉| 99/100 [36:43<00:19, 19.67s/it]

[I 2026-10-26 22:57:32,149] Trial 98 finished with value: 289.8417983077813 and parameters: {'n_estimators': 400, 'learning_rate': 0.055080093915094205, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 19, 'subsample': 0.6200886975335212, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

Best trial: 69. Best value: 288.207: 100%|██████████| 100/100 [37:06<00:00, 22.26s/it]

[I 2026-10-26 22:57:54,968] Trial 99 finished with value: 291.649258304051 and parameters: {'n_estimators': 350, 'learning_rate': 0.05517624750421039, 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 20, 'subsample': 0.6121201645084837, 'max_features': None, 'loss': 'huber'}. Best is trial 69 with value: 288.20737233298195.

========================================
BEST GRADIENT BOOSTING PARAMETERS
========================================
Best Validation RMSE:
288.20737233298195

Best Parameters:
n_estimators: 450
learning_rate: 0.06911732876051693
max_depth: 6
min_samples_split: 8
min_samples_leaf: 12
subsample: 0.6863169479272837
max_features: None
loss: huber

In [18]:
# ============================================================
# 6. Train FINAL Gradient Boosting model
# ============================================================

best_gb_params = study_gb.best_params

m_gb = GradientBoostingRegressor(
    **best_gb_params,
    random_state=42
)


# Train on ALL training data
m_gb.fit(
    X_tr_sc,
    y_train
)


# ============================================================
# 7. Predict on untouched test data
# ============================================================

pred_gb = m_gb.predict(X_te_sc)


# ============================================================
# 8. Evaluate using your existing metrics function
# ============================================================

results.append(
    metrics(
        "Gradient Boosting Optuna",
        y_test,
        pred_gb
    )
)


print("\nGradient Boosting testing completed.")

Gradient Boosting testing completed.

In [19]:
results_df = pd.DataFrame(results)
results_df

                      Model    MAE   RMSE   MAPE      R2
0  Gradient Boosting Optuna  181.5  266.4  1.534  0.9856

In [20]:
hyperparameter_summary = [
    {
        "Model": "XGBoost",
        "Search space": (
            "n_estimators∈[300, 1200] step 100; "
            "learning_rate∈[0.01, 0.10] log-scale; "
            "max_depth∈[3, 8]; "
            "min_child_weight∈[1, 15]; "
            "subsample∈[0.70, 1.0]; "
            "colsample_bytree∈[0.70, 1.0]; "
            "gamma∈[0.0, 1.0]; "
            "reg_alpha∈[1e-8, 1.0] log-scale; "
            "reg_lambda∈[1.0, 10.0] log-scale"
        ),
        "Final tuned value": study.best_params,
        "Batch size": "N/A",
        "Epochs": "N/A",
        "Optimizer": "XGBoost default optimizer",
    },
    {
        "Model": "Gradient Boosting",
        "Search space": (
            "n_estimators∈[100, 800] step 50; "
            "learning_rate∈[0.01, 0.20] log-scale; "
            "max_depth∈[2, 8]; "
            "min_samples_split∈[2, 30]; "
            "min_samples_leaf∈[1, 20]; "
            "subsample∈[0.6, 1.0]; "
            "max_features∈[None, 'sqrt', 'log2']; "
            "loss∈['squared_error', 'huber']"
        ),
        "Final tuned value": study_gb.best_params,
        "Batch size": "N/A",
        "Epochs": "N/A",
        "Optimizer": "GradientBoostingRegressor default optimizer",
    },
]

hyperparameter_table = pd.DataFrame(hyperparameter_summary)

display(hyperparameter_table)

,Model,Search space,Final tuned value,Batch size,Epochs,Optimizer
0,XGBoost,"n_estimators∈[300, 1200] step 100; learning_ra...","{'n_estimators': 900, 'learning_rate': 0.04654...",N/A,N/A,XGBoost default optimizer
1,Gradient Boosting,"n_estimators∈[100, 800] step 50; learning_rate...","{'n_estimators': 450, 'learning_rate': 0.06911...",N/A,N/A,GradientBoostingRegressor default optimizer